In [ ]:
# flatten() method is used to make 2D,3D array into 1D array(flattten)
# it returns a list of all elements in the array
# it works like copy method i.e base is None
# changes made in the original array will not be reflected in the flatten list

In [8]:
import numpy as np
arr = np.random.randint(2,200,size=(3,4))
print("Original : ",arr)
l1 = arr.flatten()
print("Flatten : ",l1)
print("Base : ",l1.base)
arr[0][0]=10
print("Change arr :",arr)
print("Changes Reflected :",l1)

Original :  [[ 68 171  24  43]
 [172  36  90 134]
 [ 93  49 195 182]]
Flatten :  [ 68 171  24  43 172  36  90 134  93  49 195 182]
Base :  None
Change arr : [[ 10 171  24  43]
 [172  36  90 134]
 [ 93  49 195 182]]
Changes Reflected : [ 68 171  24  43 172  36  90 134  93  49 195 182]


In [ ]:
# ravel() method is used to make 2D,3D array into 1D array(flattten)
# it returns a list of all elements in the array
# it works like view method i.e base is present
# changes made in the original array will be reflected in the flatten list

In [7]:
import numpy as np
arr = np.random.randint(2,200,size=(3,4))
print("Original : ",arr)
l1 = arr.ravel()
print("Flatten : ",l1)
print("Base : ",l1.base)
arr[0][0]=10
print("Change arr :",arr)
print("Changes Reflected :",l1)

Original :  [[ 76  15  43  52]
 [ 68  66  84 190]
 [165 181 101  58]]
---------------------------------
Flatten :  [ 76  15  43  52  68  66  84 190 165 181 101  58]
Base :  [[ 76  15  43  52]
 [ 68  66  84 190]
 [165 181 101  58]]
Change arr : [[ 10  15  43  52]
 [ 68  66  84 190]
 [165 181 101  58]]
Changes Reflected : [ 10  15  43  52  68  66  84 190 165 181 101  58]
