In [ ]:
# eye() method
# syntax : var = numpy.eye(n,m=None,k=None,dtype)

In [1]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
arr = np.eye(3,dtype = int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
arr = np.eye(6,k=-1,dtype=int)
print(arr)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [7]:
arr = np.eye(6,k=-2,dtype=int)
print(arr)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


In [9]:
arr = np.eye(6,k=-3,dtype=int)
print(arr)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


In [11]:
arr = np.eye(6,k=-4,dtype=int)
print(arr)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]]


In [13]:
arr = np.eye(6,k=1,dtype=int)
print(arr)

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


In [15]:
arr = np.eye(6,k=2,dtype=int)
print(arr)

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
arr = np.eye(6,k=3,dtype=int)
print(arr)

[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
arr = np.eye(6,4,k=-1,dtype=int)
print(arr)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [21]:
arr = np.eye(6,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
arr = np.eye(6,5,k=-1,dtype=int)
print(arr)