In [ ]:
# hstack() -- Horizontal stack (stacking means merging)
# syntax = var_name = numpy.hstack((ndarray1,ndarray2)) --> no.of.rows must be same 

In [91]:
import numpy as np
arr1 = np.arange(9)
arr2 = np.array([10,20,30,40,50,60,70,80,90])
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.hstack((arr1,arr2))
print("Element after horizontal(row) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [0 1 2 3 4 5 6 7 8]
Element befor merging : [10 20 30 40 50 60 70 80 90]
Element after horizontal(row) merging : [ 0  1  2  3  4  5  6  7  8 10 20 30 40 50 60 70 80 90]
Dimension of arr3 :  1
Shape of arr3 :  (18,)


In [89]:
arr1 = np.arange(9)
arr2 = np.array([10,20,30,40,50,60,70,80,90])
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.hstack((arr2,arr1))
print("Element after horizontal(row) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [0 1 2 3 4 5 6 7 8]
Element befor merging : [10 20 30 40 50 60 70 80 90]
Element after horizontal(row) merging : [10 20 30 40 50 60 70 80 90  0  1  2  3  4  5  6  7  8]
Dimension of arr3 :  1
Shape of arr3 :  (18,)


In [87]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.hstack((arr1,arr2))
print("Element after horizontal(row) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [[0 1 2]
 [3 4 5]
 [6 7 8]]
Element befor merging : [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element after horizontal(row) merging : [[ 0  1  2 10 20 30]
 [ 3  4  5 40 50 60]
 [ 6  7  8 70 80 90]]
Dimension of arr3 :  2
Shape of arr3 :  (3, 6)


In [83]:
arr1 = np.arange(10).reshape(5,2)
arr2 = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150]).reshape(5,3)
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.hstack((arr1,arr2))
print("Element after horizontal(row) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Element befor merging : [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]
 [130 140 150]]
Element after horizontal(row) merging : [[  0   1  10  20  30]
 [  2   3  40  50  60]
 [  4   5  70  80  90]
 [  6   7 100 110 120]
 [  8   9 130 140 150]]
Dimension of arr3 :  2
Shape of arr3 :  (5, 5)


In [ ]:
# vstack() method -- Vertical stack (stacking means merging)
# syntax = var_name = numpy.vstack((arr1,arr2))  -- no.of.columns must be same

In [81]:
import numpy as np
arr1 = np.arange(9)
arr2 = np.array([10,20,30,40,50,60,70,80,90])
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.vstack((arr1,arr2))
print("Element after vertical(column) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [0 1 2 3 4 5 6 7 8]
Element befor merging : [10 20 30 40 50 60 70 80 90]
Element after vertical(column) merging : [[ 0  1  2  3  4  5  6  7  8]
 [10 20 30 40 50 60 70 80 90]]
Dimension of arr3 :  2
Shape of arr3 :  (2, 9)


In [77]:
# import numpy as np
arr1 = np.arange(9).reshape(3,3)
arr2 = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.vstack((arr1,arr2))
print("Element after vertical(column) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [[0 1 2]
 [3 4 5]
 [6 7 8]]
Element befor merging : [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element after vertical(column) merging : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of arr3 :  2
Shape of arr3 :  (6, 3)


In [93]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Element befor merging :",arr1)
print("Element befor merging :",arr2)
arr3 = np.vstack((arr2,arr1))
print("Element after vertical(column) merging :",arr3)
print("Dimension of arr3 : ",arr3.ndim)
print("Shape of arr3 : ",arr3.shape)

Element befor merging : [[0 1 2]
 [3 4 5]
 [6 7 8]]
Element befor merging : [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element after vertical(column) merging : [[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]
Dimension of arr3 :  2
Shape of arr3 :  (6, 3)
