In [ ]:
# split methods
# spliting arr using numpy methods

In [6]:
import numpy as np
# split() only divide into equal parts
arr = np.array([21,34,54,67,78,89,90,9,12])
print("original arr :",arr)
print("spliting arr :",np.split(arr,3))

original arr : [21 34 54 67 78 89 90  9 12]
spliting arr : [array([21, 34, 54]), array([67, 78, 89]), array([90,  9, 12])]


In [8]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12,33])
print("original arr :",arr)
print("spliting arr :",np.split(arr,5))

original arr : [21 34 54 67 78 89 90  9 12 33]
spliting arr : [array([21, 34]), array([54, 67]), array([78, 89]), array([90,  9]), array([12, 33])]


In [10]:
import numpy as np
# array_split() used to split in both equal and unequal parts
arr = np.array([21,34,54,67,78,89,90,9,12])
print("original arr :",arr)
print("spliting arr :",np.array_split(arr,4))

original arr : [21 34 54 67 78 89 90  9 12]
spliting arr : [array([21, 34, 54]), array([67, 78]), array([89, 90]), array([ 9, 12])]


In [11]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12]).reshape(3,3)
print("original arr :",arr)
print("spliting arr :",np.split(arr,3,axis=0))

original arr : [[21 34 54]
 [67 78 89]
 [90  9 12]]
spliting arr : [array([[21, 34, 54]]), array([[67, 78, 89]]), array([[90,  9, 12]])]


In [14]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12,18]).reshape(5,2)
print("original arr :",arr)
print("spliting arr :",np.split(arr,2,axis=1))

original arr : [[21 34]
 [54 67]
 [78 89]
 [90  9]
 [12 18]]
spliting arr : [array([[21],
       [54],
       [78],
       [90],
       [12]]), array([[34],
       [67],
       [89],
       [ 9],
       [18]])]


In [18]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12]).reshape(3,3)
print("original arr :",arr)
print("spliting arr :",np.hsplit(arr,3))

original arr : [[21 34 54]
 [67 78 89]
 [90  9 12]]
spliting arr : [array([[21],
       [67],
       [90]]), array([[34],
       [78],
       [ 9]]), array([[54],
       [89],
       [12]])]


In [17]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12]).reshape(3,3)
print("original arr :",arr)
print("spliting arr :",np.vsplit(arr,3))

original arr : [[21 34 54]
 [67 78 89]
 [90  9 12]]
spliting arr : [array([[21, 34, 54]]), array([[67, 78, 89]]), array([[90,  9, 12]])]


In [34]:
# diagolan element
# diag() without

arr = np.arange(16).reshape(4,4)
print("Array :",arr)
print("Advance slicing :",arr[(0,1,2,3),(0,1,2,3)]) #Advance Slicing

Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Advance slicing : [ 0  5 10 15]


In [35]:
# diagolan element
# diag()

arr = np.arange(16).reshape(4,4)
print("Array :",arr)
print("Advance slicing :",np.diag(arr)) #Advance Slicing

Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Advance slicing : [ 0  5 10 15]


In [40]:
# tranpose matrix

arr = np.arange(16).reshape(4,4)
print("Array :",arr)
print("Transpose Matrix using T attribute:",arr.T)
print("Transpose Matrix using transpose attribute:",np.transpose(arr))

Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Transpose Matrix using T attribute: [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
Transpose Matrix using transpose attribute: [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [41]:
# tranpose matrix

arr = np.arange(8).reshape(4,2)
print("Array :",arr)
print("Transpose Matrix using T atttribute:",arr.T)
print("Transpose Matrix using transpose method:",arr.T)

Array : [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Transpose Matrix using T atttribute: [[0 2 4 6]
 [1 3 5 7]]
Transpose Matrix using transpose method: [[0 2 4 6]
 [1 3 5 7]]
