In [ ]:
# split methods
# spliting arr using numpy methods

In [6]:
import numpy as np
# split() only divide into equal parts
arr = np.array([21,34,54,67,78,89,90,9,12])
print("original arr :",arr)
print("spliting arr :",np.split(arr,3))

original arr : [21 34 54 67 78 89 90  9 12]
spliting arr : [array([21, 34, 54]), array([67, 78, 89]), array([90,  9, 12])]


In [8]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12,33])
print("original arr :",arr)
print("spliting arr :",np.split(arr,5))

original arr : [21 34 54 67 78 89 90  9 12 33]
spliting arr : [array([21, 34]), array([54, 67]), array([78, 89]), array([90,  9]), array([12, 33])]


In [10]:
import numpy as np
# array_split() used to split in both equal and unequal parts
arr = np.array([21,34,54,67,78,89,90,9,12])
print("original arr :",arr)
print("spliting arr :",np.array_split(arr,4))

original arr : [21 34 54 67 78 89 90  9 12]
spliting arr : [array([21, 34, 54]), array([67, 78]), array([89, 90]), array([ 9, 12])]


In [11]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12]).reshape(3,3)
print("original arr :",arr)
print("spliting arr :",np.split(arr,3,axis=0))

original arr : [[21 34 54]
 [67 78 89]
 [90  9 12]]
spliting arr : [array([[21, 34, 54]]), array([[67, 78, 89]]), array([[90,  9, 12]])]


In [14]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12,18]).reshape(5,2)
print("original arr :",arr)
print("spliting arr :",np.split(arr,2,axis=1))

original arr : [[21 34]
 [54 67]
 [78 89]
 [90  9]
 [12 18]]
spliting arr : [array([[21],
       [54],
       [78],
       [90],
       [12]]), array([[34],
       [67],
       [89],
       [ 9],
       [18]])]


In [18]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12]).reshape(3,3)
print("original arr :",arr)
print("spliting arr :",np.hsplit(arr,3))

original arr : [[21 34 54]
 [67 78 89]
 [90  9 12]]
spliting arr : [array([[21],
       [67],
       [90]]), array([[34],
       [78],
       [ 9]]), array([[54],
       [89],
       [12]])]


In [17]:
import numpy as np
arr = np.array([21,34,54,67,78,89,90,9,12]).reshape(3,3)
print("original arr :",arr)
print("spliting arr :",np.vsplit(arr,3))

original arr : [[21 34 54]
 [67 78 89]
 [90  9 12]]
spliting arr : [array([[21, 34, 54]]), array([[67, 78, 89]]), array([[90,  9, 12]])]
