In [5]:
# Operators

import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.add(arr1,arr2)
print("Addition :",arr3)

Array 1 : 
 [[11 46 64 72]
 [71 24 38 44]]
Array 2 : 
 [[71 59 80  9]
 [43 72 52 65]]
Addition : [[ 82 105 144  81]
 [114  96  90 109]]


In [3]:
# Operators

import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.subtract(arr1,arr2)
print("Substraction :",arr3)

Array 1 : 
 [[42 13 89 47]
 [57  6 34 38]]
Array 2 : 
 [[18 18  5 30]
 [26 22 80 86]]
Substraction : [[ 24  -5  84  17]
 [ 31 -16 -46 -48]]


In [6]:
# Operators

import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.multiply(arr1,arr2)
print("Multiply :",arr3)

Array 1 : 
 [[ 4 71 66 18]
 [53 36 73 21]]
Array 2 : 
 [[66 85 28 32]
 [60 59 89 64]]
Multiply : [[ 264 6035 1848  576]
 [3180 2124 6497 1344]]


In [1]:
# Operators

import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.add(arr1,arr2)
print("Array 3 : \n", arr3)
arr4 = np.subtract(arr1,arr2)
print("Array 4 : \n", arr4)
arr5 = np.multiply(arr1,arr2)
print("Multiply :",arr5)

Array 1 : 
 [[77 15 25 73]
 [58 23 69 26]]
Array 2 : 
 [[54 52 71 45]
 [38 49 81 42]]
Array 3 : 
 [[131  67  96 118]
 [ 96  72 150  68]]
Array 4 : 
 [[ 23 -37 -46  28]
 [ 20 -26 -12 -16]]
Multiply : [[4158  780 1775 3285]
 [2204 1127 5589 1092]]
