In [2]:
# Operators

# Addition()
import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.add(arr1,arr2)
print("Addition :",arr3)

Array 1 : 
 [[28 64  2 46]
 [14 37 71 81]]
Array 2 : 
 [[29 82 76 82]
 [43 50 21 13]]
Addition : [[ 57 146  78 128]
 [ 57  87  92  94]]


In [3]:
# Operators

# Substract()
import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.subtract(arr1,arr2)
print("Substraction :",arr3)

Array 1 : 
 [[35 49 82 52]
 [54  8 81 35]]
Array 2 : 
 [[41 87 77 89]
 [67 38 24 22]]
Substraction : [[ -6 -38   5 -37]
 [-13 -30  57  13]]


In [6]:
# Operators

# Multiply()
import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.multiply(arr1,arr2)
print("Multiply :",arr3)

Array 1 : 
 [[ 4 71 66 18]
 [53 36 73 21]]
Array 2 : 
 [[66 85 28 32]
 [60 59 89 64]]
Multiply : [[ 264 6035 1848  576]
 [3180 2124 6497 1344]]


In [4]:
# Operators

import numpy as np
arr1 = np.random.randint(2,90,size=(2,4))
arr2 = np.random.randint(2,90,size=(2,4))
print("Array 1 : \n", arr1)
print("Array 2 : \n", arr2)
arr3 = np.add(arr1,arr2)
print("Array 3 : \n", arr3)
arr4 = np.subtract(arr1,arr2)
print("Array 4 : \n", arr4)
arr5 = np.multiply(arr1,arr2)
print("Multiply :",arr5)

Array 1 : 
 [[28 56 59 27]
 [79 89  9 29]]
Array 2 : 
 [[63  9 69 38]
 [87 80 19  5]]
Array 3 : 
 [[ 91  65 128  65]
 [166 169  28  34]]
Array 4 : 
 [[-35  47 -10 -11]
 [ -8   9 -10  24]]
Multiply : [[1764  504 4071 1026]
 [6873 7120  171  145]]


In [12]:
# Operator

# each row of first matrix multiply with each column of second matrix
# dot()
# matmul()
# [[2,4],[3,5]] [[5,6],[7,8]]--->[[2*5+7*4  2*6+4*8],[3*5+7*5  3*6+8*5]]
arr1 = np.array([2,4,3,5]).reshape(2,2)
arr2 = np.array([5,6,7,8]).reshape(2,2)
print("original :\n",arr1)
print("original :\n",arr2)
print("Dot product of array is :\n",np.dot(arr1,arr2))
print("Dot product of array is :\n",np.matmul(arr1,arr2))

original :
 [[2 4]
 [3 5]]
original :
 [[5 6]
 [7 8]]
Dot product of array is :
 [[38 44]
 [50 58]]
Dot product of array is :
 [[38 44]
 [50 58]]


In [19]:
# Operator

# each row of first matrix multiply with each column of second matrix
# dot()
# matmul()
# [[2,4],[3,5]] [[5,6],[7,8]]--->[[2*5+7*4  2*6+4*8],[3*5+7*5  3*6+8*5]]
arr1 = np.random.randint(23,99,size=(2,2))
arr2 = np.random.randint(2,3,size=(2,2))
print("original :\n",arr1)
print("original :\n",arr2)
print("Dot product of array is :\n",np.dot(arr1,arr2))
print("Dot product of array is :\n",np.matmul(arr1,arr2))

original :
 [[44 75]
 [44 39]]
original :
 [[2 2]
 [2 2]]
Dot product of array is :
 [[238 238]
 [166 166]]
Dot product of array is :
 [[238 238]
 [166 166]]


In [20]:
# operator

# division()
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])
print(np.divide(arr1, arr2))  # Output: [10.  10.

[10. 10. 10. 10. 10.]


In [21]:
# operator

# division()
arr1 = np.array([10, 20, 30, 40]).reshape(2,2)
arr2 = np.array([1, 2, 3, 4]).reshape(2,2)
print(np.divide(arr1, arr2)) 

[[10. 10.]
 [10. 10.]]


In [22]:
# operator

# floor_division()
arr1 = np.array([10, 20, 30, 40]).reshape(2,2)
arr2 = np.array([1, 2, 3, 4]).reshape(2,2)
print(np.floor_divide(arr1, arr2))

[[10 10]
 [10 10]]


In [23]:
# operator

# mod()
arr1 = np.array([10, 20, 30, 40]).reshape(2,2)
arr2 = np.array([1, 2, 3, 4]).reshape(2,2)
print(np.mod(arr1, arr2))  # Output: [10.  10.

[[0 0]
 [0 0]]


In [28]:
# operator

# mod()
arr1 = np.random.randint(23,99,size=(2,2))
arr2 = np.random.randint(12,77,size=(2,2))
print(arr1,arr2,sep='\n')
print(np.mod(arr1, arr2))  # Output: [10.  10.

[[90 73]
 [47 48]]
[[16 38]
 [61 37]]
[[10 35]
 [47 11]]


In [33]:
# operator

# power()
arr1 = np.random.randint(11,19,size=(2,2))
arr2 = np.random.randint(2,3,size=(2,2))
print(arr1,arr2,sep='\n')
print(np.power(arr1, arr2))  # Output: [10.  10.

[[15 14]
 [14 18]]
[[2 2]
 [2 2]]
[[225 196]
 [196 324]]
