In [1]:
import numpy as np

In [2]:
print("Predefined Methods : Append Insert Delete")

Predefined Methods : Append Insert Delete


In [6]:
arr = np.array([12,43,3,90,6,7,778])
print("Before append :",arr)
arr = np.append(arr,223)
print("After append :",arr)


Before append : [ 12  43   3  90   6   7 778]
After append : [ 12  43   3  90   6   7 778 223]


In [7]:
arr = np.array([12,43,3,90,6,7,778])
print("Before append :",arr)
arr = np.append(arr,[1,2,3])
print("After append :",arr)


Before append : [ 12  43   3  90   6   7 778]
After append : [ 12  43   3  90   6   7 778   1   2   3]


In [15]:
print('Appending Row ')
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before append :\n",arr)
arr = np.append(arr,[[1,2,3]],axis=0)
print("After append :\n",arr)


Appending Row 
Before append :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After append :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]
 [  1   2   3]]


In [14]:
print("Appending Coulmn ")
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before append :\n",arr)
arr = np.append(arr,[[1],[2],[3]],axis=1)
print("After append :\n",arr)


Appending Coulmn 
Before append :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After append :
 [[ 12  43   3   1]
 [ 90   6   7   2]
 [778  76   4   3]]


In [18]:
print("Appending Row ")
arr = np.array([12,43,3,90,6,7,778,76,4,11,43,66]).reshape(3,4)
print("Before append :\n",arr)
arr = np.append(arr,[[1,2,12,3]],axis=0)
print("After append :\n",arr)


Appending Row 
Before append :
 [[ 12  43   3  90]
 [  6   7 778  76]
 [  4  11  43  66]]
After append :
 [[ 12  43   3  90]
 [  6   7 778  76]
 [  4  11  43  66]
 [  1   2  12   3]]


In [21]:
# insert()
arr = np.array([12,43,3,90,6,7,778,76,4])
print("Before insert :\n",arr)
arr = np.insert(arr,3,[12,34])
print("After insert :\n",arr)


Before insert :
 [ 12  43   3  90   6   7 778  76   4]
After insert :
 [ 12  43   3  12  34  90   6   7 778  76   4]


In [22]:
# insert()
arr = np.array([12,43,3,90,6,7,778,76,4])
print("Before insert :\n",arr)
arr = np.insert(arr,[2,4],[12,34])
print("After insert :\n",arr)


Before insert :
 [ 12  43   3  90   6   7 778  76   4]
After insert :
 [ 12  43  12   3  90  34   6   7 778  76   4]


In [23]:
# insert()
arr = np.array([12,43,3,90,6,7,778,76,4])
print("Before insert :\n",arr)
arr = np.insert(arr,[0,-1],[12,34])
print("After insert :\n",arr)


Before insert :
 [ 12  43   3  90   6   7 778  76   4]
After insert :
 [ 12  12  43   3  90   6   7 778  76  34   4]


In [24]:
# insert()
print("Insert in row ")
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before insert :\n",arr)
arr = np.insert(arr,1,[[12,34,2]],axis=0)
print("After insert :\n",arr)


Before insert :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After insert :
 [[ 12  43   3]
 [ 12  34   2]
 [ 90   6   7]
 [778  76   4]]


In [26]:
# insert()
print("Insert in Column ")
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before insert :\n",arr)
arr = np.insert(arr,1,[[11,11,11]],axis=1)
print("After insert :\n",arr)


Insert in Column 
Before insert :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After insert :
 [[ 12  11  43   3]
 [ 90  11   6   7]
 [778  11  76   4]]


In [27]:
# insert()
print("Insert in Column ")
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before insert :\n",arr)
arr = np.insert(arr,2,[[85,90,121]],axis=1)
print("After insert :\n",arr)


Insert in Column 
Before insert :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After insert :
 [[ 12  43  85   3]
 [ 90   6  90   7]
 [778  76 121   4]]


In [31]:
# insert()
print("Insert in Row ")
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before insert :\n",arr)
arr = np.insert(arr,[0,2],[[1,1,1],[11,11,11]],axis=0)
print("After insert :\n",arr)


Insert in Row 
Before insert :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After insert :
 [[  1   1   1]
 [ 12  43   3]
 [ 90   6   7]
 [ 11  11  11]
 [778  76   4]]


In [39]:
# insert()
print("Insert in Column ")
arr = np.array([12,43,33,3,90,6]).reshape(2,3)
print("Before insert :\n",arr)
arr = np.insert(arr,[0,1],[[1,1],[11,11]],axis=1)
print("After insert :\n",arr)


Insert in Column 
Before insert :
 [[12 43 33]
 [ 3 90  6]]
After insert :
 [[ 1 12  1 43 33]
 [11  3 11 90  6]]


In [42]:
# insert()
print("Insert in Column ")
arr = np.array([12,43,3,90,6,7,778,76,4]).reshape(3,3)
print("Before insert :\n",arr)
arr = np.insert(arr,[0,1,2],[[1,1,1,],[11,11,11],[2,2,2]],axis=1)
print("After insert :\n",arr)


Insert in Column 
Before insert :
 [[ 12  43   3]
 [ 90   6   7]
 [778  76   4]]
After insert :
 [[  1  12   1  43   1   3]
 [ 11  90  11   6  11   7]
 [  2 778   2  76   2   4]]


In [43]:
# delete()

print("Delete in matrix ")
arr = np.array([12,43,33,3,90,6])
print("Before delete :\n",arr)
arr = np.delete(arr,2)
print("After delete :\n",arr)


Insert in Column 
Before insert :
 [12 43 33  3 90  6]
After delete :
 [12 43  3 90  6]


In [44]:
# delete()

print("Delete in matrix ")
arr = np.array([12,43,33,3,90,6])
print("Before delete :\n",arr)
arr = np.delete(arr,-2)
print("After delete :\n",arr)


Delete in matrix 
Before delete :
 [12 43 33  3 90  6]
After delete :
 [12 43 33  3  6]


In [46]:
# delete()

print("Delete Multiple element in matrix ")
arr = np.array([12,43,33,3,90,6])
print("Before delete :\n",arr)
arr = np.delete(arr,[-1,3,-2])
print("After delete :\n",arr)


Delete Multiple element in matrix 
Before delete :
 [12 43 33  3 90  6]
After delete :
 [12 43 33]


In [51]:
# delete()

print("Delete row in matrix ")
arr = np.array([12,43,33,3,90,6]).reshape(3,2)
print("Before delete :\n",arr)
arr = np.delete(arr,0,axis=0)
print("After delete :\n",arr)


Delete in matrix 
Before delete :
 [[12 43]
 [33  3]
 [90  6]]
After delete :
 [[33  3]
 [90  6]]


In [52]:
# delete()

print("Delete col in matrix ")
arr = np.array([12,43,33,3,90,6]).reshape(3,2)
print("Before delete :\n",arr)
arr = np.delete(arr,0,axis=1)
print("After delete :\n",arr)


Delete col in matrix 
Before delete :
 [[12 43]
 [33  3]
 [90  6]]
After delete :
 [[43]
 [ 3]
 [ 6]]
