In [1]:
# linear algebra
import numpy as np
import numpy.linalg as al
print("Hello linear Algebra!")

Hello linear algebra!


In [2]:
# dot() product 
arr1 = np.array([1,2,3])
arr2 = np.array([3,2,1])
arr3 = np.dot(arr1,arr2)
print(arr3)  # Output: 14

10


In [6]:
# inner() inner product of matrix 
# calculate row with row (arr1 1 row with arr2 1 row)
arr1 = np.array([11,3,5,6]).reshape(2,2)
arr2 = np.array([3,4,9,21]).reshape(2,2)
arr3 = np.inner(arr1,arr2)
print(arr1,arr2)
print(arr3)

[[11  3]
 [ 5  6]] [[ 3  4]
 [ 9 21]]
[[ 45 162]
 [ 39 171]]


In [8]:
# inner() inner product of matrix 
# inner product of 1D and dot product of !D is same
# calculate row with row (arr1 1 row with arr2 1 row)
arr1 = np.array([11,3,5,2,5,6]).reshape(3,2)
arr2 = np.array([3,4,9,21,8,9]).reshape(3,2)
arr3 = np.inner(arr1,arr2)
print(arr1,arr2)
print(arr3)

[[11  3]
 [ 5  2]
 [ 5  6]] [[ 3  4]
 [ 9 21]
 [ 8  9]]
[[ 45 162 115]
 [ 23  87  58]
 [ 39 171  94]]


In [10]:
# inner() inner product of matrix 
# inner product of 1D and dot product of !D is same
# calculate row with row (arr1 1 row with arr2 1 row)
arr1 = np.array([11,3,5,6])
arr2 = np.array([3,4,9,21])
arr3 = np.inner(arr1,arr2)
print(arr1,arr2)
print("Inner od 1D :",arr3)

[11  3  5  6] [ 3  4  9 21]
Inner od 1D : 216


In [11]:
# outer() outer product of matrix 
# multipy each element of arr1 with each element of arr2
arr1 = np.array([11,3,5,6])
arr2 = np.array([3,4,9,21])
arr3 = np.outer(arr1,arr2)
print(arr1,arr2)
print(arr3)

[11  3  5  6] [ 3  4  9 21]
[[ 33  44  99 231]
 [  9  12  27  63]
 [ 15  20  45 105]
 [ 18  24  54 126]]


In [12]:
# outer() outer product of matrix 
# multipy each element of arr1 with each element of arr2
arr1 = np.array([11,3,5,6]).reshape(2,2)
arr2 = np.array([3,4,9,21]).reshape(2,2)
arr3 = np.outer(arr1,arr2)
print(arr1,arr2)
print(arr3)

[[11  3]
 [ 5  6]] [[ 3  4]
 [ 9 21]]
[[ 33  44  99 231]
 [  9  12  27  63]
 [ 15  20  45 105]
 [ 18  24  54 126]]


In [19]:
# det()
# finding determinent
arr = np.array([1,3,5,9]).reshape(2,2)
D = np.linalg.det(arr)
print(arr)
print("Determinant :",D)

[[1 3]
 [5 9]]
Determinant : -6.0


In [20]:
# det()
# finding determinent
arr = np.array([1,3,5,9,2,3,4,5,6]).reshape(3,3)
D = np.linalg.det(arr)
print(arr)
print("Determinant :",D)

[[1 3 5]
 [9 2 3]
 [4 5 6]]
Determinant : 56.00000000000002


In [21]:
# solve()
# used to solve linear equations
# 2x+3y=4 and 5x+6y=4 
arr1 = np.array([[2,3],[5,6]])
arr2 = np.array([4,4])
arr3 = np.linalg.solve(arr1,arr2)
print(arr1,arr2)
print(arr3) 

[[2 3]
 [5 6]] [4 4]
[-4.  4.]


In [23]:
# solve()
# used to solve linear equations
# 2x+3y+z=4 and 5x+6y-z=4 
arr1 = np.array([[2,3,1],[5,6,-1],[1,2,3]])
arr2 = np.array([4,4,4])
arr3 = np.linalg.solve(arr1,arr2)
print(arr1,arr2)
print(arr3) 

[[ 2  3  1]
 [ 5  6 -1]
 [ 1  2  3]] [4 4 4]
[-4.00000000e+00  4.00000000e+00 -8.43769499e-16]


In [28]:
# inv()
# 2x+3y=4 and 5x+6y=4 
arr1 = np.array([[2,3],[6,1]])
arr3 = np.linalg.inv(arr1)
print("Original :",arr1)
print("Inverse :",arr3) 

Original : [[2 3]
 [6 1]]
Inverse : [[-0.0625  0.1875]
 [ 0.375  -0.125 ]]


In [29]:
# inv()
arr1 = np.array([[2,3],[2,2]])
arr3 = np.linalg.inv(arr1)
print("Original :",arr1)
print("Inverse :",arr3) 

Original : [[2 3]
 [2 2]]
Inverse : [[-1.   1.5]
 [ 1.  -1. ]]


In [30]:
# solve()
# used to solve linear equations
# 2x+3y=4 and 5x+6y=4 
arr1 = np.array([[2,3],[5,6]])
arr2 = np.array([4,4])
arr3 = np.dot(arr2,np.linalg.inv(arr1))
print(arr1,arr2)
print(arr3) 

[[2 3]
 [5 6]] [4 4]
[-1.33333333  1.33333333]


In [35]:
# trace() used to give sum of diagonal elements
arr1 = np.array([12,21,9,6]).reshape(2,2)
print("Original array is: ", arr1)
print(np.trace(arr1))

Original array is:  [[12 21]
 [ 9  6]]
18


In [37]:
# trace() used to give sum of diagonal elements
arr1 = np.array([12,21,9,6,45,46,5,56,4]).reshape(3,3)
print("Original array is: ", arr1)
print(np.trace(arr1))

Original array is:  [[12 21  9]
 [ 6 45 46]
 [ 5 56  4]]
61
