In [1]:
import numpy as np
# addition and summation

In [2]:
# addition 
arr1 = np.array([1,2,4,6])
arr2 = np.array([1,3,8,6])
arr3 = np.add(arr1,arr2)
print(f"Addtion of {arr1} + {arr2} = {arr3}")


Addtion of [1 2 4 6] + [1 3 8 6] = [ 2  5 12 12]


In [3]:
# addition 
arr1 = np.array([1,2,4,6]).reshape(2,2)
arr2 = np.array([1,3,8,6]).reshape(2,2)
arr3 = np.add(arr1,arr2)
print(f"Addtion of {arr1} + {arr2} = {arr3}")


Addtion of [[1 2]
 [4 6]] + [[1 3]
 [8 6]] = [[ 2  5]
 [12 12]]


In [9]:
# sum
arr1 = np.array([1,2,4,6]) #sum = 13
arr2 = np.array([1,3,8,6]) #sum = 18
# Total sum = 31
arr3 = np.sum([arr1,arr2])
print(f"Summation of {arr1} + {arr2} = {arr3}")


Summation of [1 2 4 6] + [1 3 8 6] = 31


In [14]:
# sum
arr1 = np.array([1,2,4,6]).reshape(2,2) #sum = 1+4 =5 , 2+6 = 8
arr2 = np.array([1,3,8,6]).reshape(2,2) #sum = 1+8 = 9 , 3+6 = 9
# Total sum = [13,18]
arr3 = np.sum([arr1,arr2],axis=1) #col-col sum
print(f"Summation of \n{arr1}\n +\n {arr2}\n =\n {arr3}")


Summation of 
[[1 2]
 [4 6]]
 +
 [[1 3]
 [8 6]]
 =
 [[5 8]
 [9 9]]


In [12]:
# sum
arr1 = np.array([1,2,4,6]).reshape(2,2) #sum = 1+1=1 , 2+3=5
arr2 = np.array([1,3,8,6]).reshape(2,2) #sum = 4+8=12 , 6+6=12
# Total sum = [13,18]
arr3 = np.sum([arr1,arr2],axis=0) # rwo-row sum
print(f"Summation of {arr1} + {arr2} = {arr3}")


Summation of [[1 2]
 [4 6]] + [[1 3]
 [8 6]] = [[ 2  5]
 [12 12]]


In [18]:
# cumsum()
# sum
arr1 = np.array([1,2,4,6]) #sum = 13
arr2 = np.array([1,3,8,6]) #sum = 18
# Total sum = [13,18]
arr3 = np.cumsum([arr1,arr2])
print(f"Summation of {arr1} + {arr2} =\n {arr3}")


Summation of [1 2 4 6] + [1 3 8 6] =
 [ 1  3  7 13 14 17 25 31]


In [22]:
# product --> prod()
arr = np.array([1,2,3,4])
print("Array :",arr)
p = np.prod(arr)  # Output: 24
print("Product :",p)


Array : [1 2 3 4]
Product : 24


In [23]:
# cumsum()
# sum
arr1 = np.array([1,2,4,6]) 
arr2 = np.array([1,3,8,6])
arr3 = np.prod([arr1,arr2])
print(f"Product of {arr1} + {arr2} =\n {arr3}")


Summation of [1 2 4 6] + [1 3 8 6] =
 6912


In [30]:
# cumsum()
# sum
arr1 = np.array([1,2,4,6]).reshape(2,2)
arr2 = np.array([1,3,8,6]).reshape(2,2)
arr3 = np.prod([arr1,arr2],axis=0) # element to element row wise multiplication
print(f"Probuct of {arr1} + {arr2} =\n {arr3}")


Probuct of [[1 2]
 [4 6]] + [[1 3]
 [8 6]] =
 [[ 1  6]
 [32 36]]


In [29]:
# cumsum()
# sum
arr1 = np.array([1,2,4,6]).reshape(2,2)
arr2 = np.array([1,3,8,6]).reshape(2,2)
arr3 = np.prod([arr1,arr2],axis=1) # element to element col wise multiplication
print(f"Product of {arr1} + {arr2} =\n {arr3}")


Product of [[1 2]
 [4 6]] + [[1 3]
 [8 6]] =
 [[ 4 12]
 [ 8 18]]


In [32]:
# cumsum()
# sum
arr1 = np.array([1,2,4,6])
arr3 = np.cumprod([arr1]) # element to element row wise multiplication
print(f"Cumulative product of {arr1} =\n {arr3}")


Cumulative product of [1 2 4 6] =
 [ 1  2  8 48]


In [42]:
# cumsum()
# sum
arr1 = np.array([1,2,3,3,4,5,2,3,5]).reshape(3,3)
arr3 = np.cumprod(arr1,axis=0) # element to element col wise multiplication
print(arr1)
print(arr3)


[[1 2 3]
 [3 4 5]
 [2 3 5]]
[[ 1  2  3]
 [ 3  8 15]
 [ 6 24 75]]


In [43]:
# cumsum()
# sum
arr1 = np.array([1,2,3,3,4,5,2,3,5]).reshape(3,3)
arr3 = np.cumprod(arr1,axis=1) # element to element row wise multiplication
print(arr1)
print(arr3)


[[1 2 3]
 [3 4 5]
 [2 3 5]]
[[ 1  2  6]
 [ 3 12 60]
 [ 2  6 30]]
