In [6]:
# 3D slicing
import numpy as np
arr = np.array([12,34,56,78,90,32,54,87,1,6,56,78,90,32,54,87]).reshape(4,4)
print(arr)
print(f"Dimension of array : {arr.ndim}")
print(f"Size of array : {arr.size}")
print(f"Shape of array : {arr.shape}")

[[12 34 56 78]
 [90 32 54 87]
 [ 1  6 56 78]
 [90 32 54 87]]
Dimension of array : 2
Size of array : 16
Shape of array : (4, 4)


In [10]:
# last 2 rows
arr[2:,:], arr[::3,1:2]

(array([[ 1,  6, 56, 78],
        [90, 32, 54, 87]]),
 array([[34],
        [32]]))

In [1]:
# advance slicing
import numpy as np
arr = np.array([12,34,56,78,90,32,54,87,1,6,56,78,90,32,54,87]).reshape(2,4,2)
print(arr)
print(f"Dimension of array : {arr.ndim}")
print(f"Size of array : {arr.size}")
print(f"Shape of array : {arr.shape}")

[[[12 34]
  [56 78]
  [90 32]
  [54 87]]

 [[ 1  6]
  [56 78]
  [90 32]
  [54 87]]]
Dimension of array : 3
Size of array : 16
Shape of array : (2, 4, 2)


In [12]:
arr[:1,1:3,:],arr[:1,1:3],arr[:1,::3,:1],arr[:,:1,:],arr[:,1:3,:]

(array([[[56, 78],
         [90, 32]]]),
 array([[[56, 78],
         [90, 32]]]),
 array([[[12],
         [54]]]),
 array([[[12, 34]],
 
        [[ 1,  6]]]),
 array([[[56, 78],
         [90, 32]],
 
        [[56, 78],
         [90, 32]]]))

In [13]:
# advance slicing
import numpy as np
arr = np.array([12,34,56,78,90,32,54,87,1,6,56,78,90,32,54,87]).reshape(2,2,2,2)
print(arr)
print(f"Dimension of array : {arr.ndim}")
print(f"Size of array : {arr.size}")
print(f"Shape of array : {arr.shape}")

[[[[12 34]
   [56 78]]

  [[90 32]
   [54 87]]]


 [[[ 1  6]
   [56 78]]

  [[90 32]
   [54 87]]]]
Dimension of array : 4
Size of array : 16
Shape of array : (2, 2, 2, 2)


In [16]:
arr[:,:,:,:],arr[:,:,:1,:],arr[:,:,:1,1:]

(array([[[[12, 34],
          [56, 78]],
 
         [[90, 32],
          [54, 87]]],
 
 
        [[[ 1,  6],
          [56, 78]],
 
         [[90, 32],
          [54, 87]]]]),
 array([[[[12, 34]],
 
         [[90, 32]]],
 
 
        [[[ 1,  6]],
 
         [[90, 32]]]]),
 array([[[[34]],
 
         [[32]]],
 
 
        [[[ 6]],
 
         [[32]]]]))