In [1]:
# Advance slicing on numpy
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr)

[10 20 30 40 50 60 70]


In [2]:
# Step for advance indexing 
# 1 : identify the index of the element you want to access
# 2 : pass that indexs to ndarray object
# Advance slicing on numpy
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr)

[10 20 30 40 50 60 70]


In [5]:
# i want to access 10,40,50 
# 1 : identify the index of the element you want to access
lst = [0,3,4] # take index of values in list
# 2 : pass that indexs to ndarray object
arr[lst],arr[[0,3,4]]

(array([10, 40, 50]), array([10, 40, 50]))

In [6]:
arr[[-1,-2,1,0]]

array([70, 60, 20, 10])

In [18]:
# Advance slicing on numpy
import numpy as np
arr = np.random.randint(1,100,size=(5,5))
print(arr)

[[29 64  9 29 46]
 [68 13 68 93 72]
 [31 68 38 56  5]
 [34 46 55 29 32]
 [27 18 55 91 40]]


In [23]:
# want 64 38 55 40
# step-1 : first collect row element diagonal elements row = [0,1,2,3,4]
# step-2 : second collect col element diagonal elements col = [0,1,2,3,4]
# step-3 : pass row_indices and col_indices to ndarray object
row_index = [0,2,4,4]
col_index = [1,2,2,4]
arr[row_index,col_index]

array([64, 38, 55, 40])

In [24]:
# step-1 : first collect row element diagonal elements row = [0,1,2,3,4]
# step-2 : second collect col element diagonal elements col = [0,1,2,3,4]
# step-3 : pass row_indices and col_indices to ndarray object
arr[[0,1,2,3,4],[0,1,2,3,4]] , arr[[4,3,2,1,0],[0,1,2,3,4]]

(array([29, 13, 38, 29, 40]), array([27, 46, 38, 93, 46]))

In [30]:
# Advance slicing on numpy
import numpy as np
arr = np.random.randint(1,100,size=(3,3,3))
print(arr)

[[[53 93 37]
  [69 77 82]
  [52 28 97]]

 [[34 10 33]
  [91 80 10]
  [89 34 15]]

 [[88 54 43]
  [94 56 93]
  [ 7 18 84]]]


In [39]:
arr[[0,0,2],[0,2,2],[0,2,0]],arr[[0,0,2,2],[0,2,2,0],[0,2,0,2]]

(array([53, 97,  7]), array([53, 97,  7, 43]))

In [41]:
# Advance slicing on numpy
import numpy as np
arr = np.random.randint(1,100,size=(2,2,3,3))
print(arr)

[[[[68 49 22]
   [98 13  6]
   [74 57 61]]

  [[46 20 15]
   [20 81 56]
   [52 49 32]]]


 [[[92 32 33]
   [83 12 88]
   [65 17 70]]

  [[75 17 38]
   [67 45 37]
   [96 48 29]]]]
