In [2]:
# indexing and sciling in ndarray()
import numpy as np
arr = np.array([12,45,32,67,978,54,343,654,89,7657,8])
print(f"Array : {arr}")
print(f"Dimension of arr : {arr.ndim}")
print(f"Shape of arr : {arr.shape}")
print(f"Size of arr : {arr.size}")

Array : [  12   45   32   67  978   54  343  654   89 7657    8]
Dimension of arr : 1
Shape of arr : (11,)
Size of arr : 11


In [4]:
# get 89 using indexing
print(arr[-3])  # prints 89

89


In [6]:
# get 89 using indexing
print(arr[len(arr)-1-2])  # prints 89

89


In [7]:
# get 12 using indexing
print(arr[0]) # prints 12

12


In [9]:
# get 12 using indexing
print(arr[-len(arr)]) # prints 12

12


In [16]:
# indexing and slicing in 2D ndarray
arr = np.random.choice(100,size=(3,4))
print(f"Array : {arr}")
print(f"Dimension of arr : {arr.ndim}")
print(f"Shape of arr : {arr.shape}")
print(f"Size of arr : {arr.size}")

Array : [[66 60 53 72]
 [ 4 37 15 65]
 [ 3 91 81 63]]
Dimension of arr : 2
Shape of arr : (3, 4)
Size of arr : 12


In [26]:
# get 60 
print(arr[0,1],arr[0,-3],arr[-3,1],arr[-3,-3]) 

60 60 60 60


In [27]:
# get 60 
print(arr[0][-3],arr[-3][-3],arr[0][1],arr[-3][1])

60 60 60 60


In [31]:
# get 81
print(arr[2,2],arr[2,-2],arr[-1,-2],arr[-1,2]) 

81 81 81 81


In [32]:
# get 81
print(arr[2][2],arr[2][-2],arr[-1][-2],arr[-1][2]) 

81 81 81 81


In [33]:
# indexing and slicing in 3D ndarray
arr = np.random.choice(100,size=(3,3,4))
print(f"Array : {arr}")
print(f"Dimension of arr : {arr.ndim}")
print(f"Shape of arr : {arr.shape}")
print(f"Size of arr : {arr.size}")

Array : [[[73 80 66 85]
  [65 99 22 66]
  [52 14 89 92]]

 [[28  8 97 23]
  [35 83  5 66]
  [75 14 94 33]]

 [[85  3 49 83]
  [29 81 65 19]
  [19 49  3 29]]]
Dimension of arr : 3
Shape of arr : (3, 3, 4)
Size of arr : 36


In [40]:
# get 5
print(arr[1,1,2],arr[1,1,-2],arr[1,-2,-2],arr[-2,-2,-2],arr[-2,1,-2],arr[-2,-2,2])

5 5 5 5 5 5


In [41]:
# get 5
print(arr[1][1][2],arr[1][1][-2],arr[1][-2][-2],arr[-2][-2][-2],arr[-2][1][-2],arr[-2][-2][2])

5 5 5 5 5 5


In [47]:
# get 3
print(arr[2,0,1],arr[2,0,-3],arr[2,-3,-3],arr[-1,0,1],arr[-1,0,-3],arr[-1,-3,-3])

3 3 3 3 3 3


In [48]:
# get first matrix
print(arr[0])

[[73 80 66 85]
 [65 99 22 66]
 [52 14 89 92]]


In [49]:
# get first matrix
print(arr[-1])

[[85  3 49 83]
 [29 81 65 19]
 [19 49  3 29]]
