In [ ]:
# Iterating numpy object 

In [5]:
# iterate the data of ndarray object using for loop
# 1D
import numpy as np
arr = np.random.randint(2,55,12)
print("Original Data : ", arr)
print("Dimension : ", arr.ndim)
print("Iterable data :")
for i in arr:
    print(i,end=' ')

Original Data :  [21 50 38 30 11 33 18 53 10 51 38  5]
Dimension :  1
Iterable data :
21 50 38 30 11 33 18 53 10 51 38 5 

In [9]:
# iterate the data of ndarray object using for loop
# 2D
import numpy as np
arr = np.random.randint(2,55,size=(3,3))
print("Original Data : ", arr)
print("Dimension : ", arr.ndim)
print("Iterable data :")
for row in arr:
    for val in row:
        print("\t",val, end=" ")
    print()

Original Data :  [[10 34  4]
 [35 47 41]
 [33 51 47]]
Dimension :  2
Iterable data :
	 10 	 34 	 4 
	 35 	 47 	 41 
	 33 	 51 	 47 


In [12]:
# iterate the data of ndarray object using for loop
# 3D
import numpy as np
arr = np.random.randint(2,55,size=(2,3,3))
print("Original Data : ", arr)
print("Dimension : ", arr.ndim)
print("Iterable data :")
for matrix in arr:
    for row in matrix:
        for col in row:
            print("\t",col, end=" ")
        print()
    print()

Original Data :  [[[54  9 15]
  [36 49 19]
  [34 24 13]]

 [[36 51 29]
  [28 45 26]
  [50 36 10]]]
Dimension :  3
Iterable data :
	 54 	 9 	 15 
	 36 	 49 	 19 
	 34 	 24 	 13 

	 36 	 51 	 29 
	 28 	 45 	 26 
	 50 	 36 	 10 



In [13]:
# iterate the data of ndarray object using for loop

import numpy as np
arr = np.random.randint(2,55,size=(2,2,2,2))
print("Original Data : ", arr)
print("Dimension : ", arr.ndim)
print("Iterable data :")
for cluster in arr:
    for matrix in cluster:
        for row in matrix:
            for col in row:
                print("\t",col, end=" ")
            print()
        print()
    print()

Original Data :  [[[[39 24]
   [41 29]]

  [[28  8]
   [ 2 19]]]


 [[[39 31]
   [ 6 31]]

  [[20  3]
   [18 42]]]]
Dimension :  4
Iterable data :
	 39 	 24 
	 41 	 29 

	 28 	 8 
	 2 	 19 


	 39 	 31 
	 6 	 31 

	 20 	 3 
	 18 	 42 




In [16]:
# using numpy.nditer() method
# 1D
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
print("Array : ", arr)
print("Dimension :",arr.ndim)
for val in np.nditer(arr):
    print(val)

Array :  [10 20 30 40 50 60 70 80 90]
Dimension : 1
10
20
30
40
50
60
70
80
90


In [19]:
# using numpy.nditer() method
# 2D
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Array : ", arr)
print("Dimension :",arr.ndim)
for val in np.nditer(arr):
    print(val,end=' ')

Array :  [[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension : 2
10 20 30 40 50 60 70 80 90 

In [20]:
# using numpy.nditer() method
# 2D
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90,100,200,300,400,500,6000,700,800,900]).reshape(2,3,3)
print("Array : ", arr)
print("Dimension :",arr.ndim)
for val in np.nditer(arr):
    print(val,end=' ')

Array :  [[[  10   20   30]
  [  40   50   60]
  [  70   80   90]]

 [[ 100  200  300]
  [ 400  500 6000]
  [ 700  800  900]]]
Dimension : 3
10 20 30 40 50 60 70 80 90 100 200 300 400 500 6000 700 800 900 

In [27]:
# using numpy.ndenumerate()
# 1D
import numpy as np
arr = np.arange(20,31)
print("Original :",arr)
print("Dimension :",arr.ndim)
for i, value in np.ndenumerate(arr):
    print(f"Index: {i}, Value: {value}")

Original : [20 21 22 23 24 25 26 27 28 29 30]
Dimension : 1
Index: (0,), Value: 20
Index: (1,), Value: 21
Index: (2,), Value: 22
Index: (3,), Value: 23
Index: (4,), Value: 24
Index: (5,), Value: 25
Index: (6,), Value: 26
Index: (7,), Value: 27
Index: (8,), Value: 28
Index: (9,), Value: 29
Index: (10,), Value: 30


In [28]:
# using numpy.ndenumerate()
# 2D
import numpy as np
arr = np.arange(21,30).reshape(3,3)
print("Original :",arr)
print("Dimension :",arr.ndim)
for i, value in np.ndenumerate(arr):
    print(f"Index: {i}, Value: {value}")

Original : [[21 22 23]
 [24 25 26]
 [27 28 29]]
Dimension : 2
Index: (0, 0), Value: 21
Index: (0, 1), Value: 22
Index: (0, 2), Value: 23
Index: (1, 0), Value: 24
Index: (1, 1), Value: 25
Index: (1, 2), Value: 26
Index: (2, 0), Value: 27
Index: (2, 1), Value: 28
Index: (2, 2), Value: 29


In [29]:
# using numpy.ndenumerate()
# 3D
import numpy as np
arr = np.arange(21,39).reshape(2,3,3)
print("Original :",arr)
print("Dimension :",arr.ndim)
for i, value in np.ndenumerate(arr):
    print(f"Index: {i}, Value: {value}")

Original : [[[21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]
Dimension : 3
Index: (0, 0, 0), Value: 21
Index: (0, 0, 1), Value: 22
Index: (0, 0, 2), Value: 23
Index: (0, 1, 0), Value: 24
Index: (0, 1, 1), Value: 25
Index: (0, 1, 2), Value: 26
Index: (0, 2, 0), Value: 27
Index: (0, 2, 1), Value: 28
Index: (0, 2, 2), Value: 29
Index: (1, 0, 0), Value: 30
Index: (1, 0, 1), Value: 31
Index: (1, 0, 2), Value: 32
Index: (1, 1, 0), Value: 33
Index: (1, 1, 1), Value: 34
Index: (1, 1, 2), Value: 35
Index: (1, 2, 0), Value: 36
Index: (1, 2, 1), Value: 37
Index: (1, 2, 2), Value: 38


In [31]:
# using numpy.ndenumerate()
# 2D
import numpy as np
arr = np.arange(21,30).reshape(3,3)
print("Original :",arr)
print("Dimension :",arr.ndim)
for i, value in np.ndenumerate(arr):
    if value == 25:
        print(f"Index: {i}, Value: {value}")

Original : [[21 22 23]
 [24 25 26]
 [27 28 29]]
Dimension : 2
Index: (1, 1), Value: 25
