In [3]:
# condition based data
import numpy as np
arr = np.random.randint(2,99,25)
print("original array :",arr)

original array : [41 33 77 24 19 85 83 94 82 92 62 64 80 60 44 61 98 41 21 48 60 18 38 36
 83]


In [6]:
# only even number in array
barr = arr%2==0 # it create boolean array
print("Boolean array :",barr)
"Even numbers array :",arr[barr]

Boolean array : [False False False  True False False False  True  True  True  True  True
  True  True  True False  True False False  True  True  True  True  True
 False]


('Even numbers array :',
 array([24, 94, 82, 92, 62, 64, 80, 60, 44, 98, 48, 60, 18, 38, 36]))

In [7]:
# only odd number in array
barr = arr%2!=0 # it create boolean array
print("Boolean array :",barr)
"Odd numbers array :",arr[barr]

Boolean array : [ True  True  True False  True  True  True False False False False False
 False False False  True False  True  True False False False False False
  True]


('Odd numbers array :', array([41, 33, 77, 19, 85, 83, 61, 41, 21, 83]))

In [9]:
# only multiple of 3 in array
barr = arr%3==0 # it create boolean array
print("Boolean array :",barr)
"Multiple of 3 array :",arr[barr]

Boolean array : [False  True False  True False False False False False False False False
 False  True False False False False  True  True  True  True False  True
 False]


('Multiple of 3 array :', array([33, 24, 60, 21, 48, 60, 18, 36]))

In [10]:
# only multiple of 5 in array
barr = arr%5==0 # it create boolean array
print("Boolean array :",barr)
"Multiple of 5 array :",arr[barr]

Boolean array : [False False False False False  True False False False False False False
  True  True False False False False False False  True False False False
 False]


('Multiple of 5 array :', array([85, 80, 60, 60]))

In [13]:
# only multiple of both 3 and 5 in array
barr = (arr%3==0) & (arr%5==0) # it create boolean array
print("Boolean array :",barr)
"Multiple of 3 and 5 array :",arr[barr]

Boolean array : [False False False False False False False False False False False False
 False  True False False False False False False  True False False False
 False]


('Multiple of 3 and 5 array :', array([60, 60]))

In [15]:
# where method

arr = np.array([1,2,3,4,5,6,7,8,-1,-2,-3,-4,5,-5,-6])
idx = np.where(arr > 0)
print(idx , type(idx)) # return tuple of arrays
for i in idx[0]: # idx[0] contain the index of the array where the condition is true
    print(i,end=' ')

(array([ 0,  1,  2,  3,  4,  5,  6,  7, 12], dtype=int64),) <class 'tuple'>
0 1 2 3 4 5 6 7 12 

In [18]:
# where method

arr = np.arange(4,41,4)
idx = np.where(arr%4==0)
print(idx , type(idx)) # return tuple of arrays
for i in idx[0]: # idx[0] contain the index of the array where the condition is true
    print(i,end=' ')

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),) <class 'tuple'>
0 1 2 3 4 5 6 7 8 9 

In [24]:
# where method
# syntax : numpy.where(condition)
# syntax-2 : numpy.where(condition,x,y)
arr = np.arange(4,400,8)
idx = np.where(arr%4==0)
print(idx , type(idx)) # return tuple of arrays
for i in idx[0]: # idx[0] contain the index of the array where the condition is true
    print(i,end=' ')

(array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49],
      dtype=int64),) <class 'tuple'>
1 4 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 

In [25]:
# where method
# syntax : numpy.where(condition)
# syntax-2 : numpy.where(condition,x,y)
arr = np.arange(4,400,8)
idx = np.where((arr%4==0) & (arr%6==0))
print(idx , type(idx)) # return tuple of arrays
for i in idx[0]: # idx[0] contain the index of the array where the condition is true
    print(i,end=' ')

(array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49],
      dtype=int64),) <class 'tuple'>
1 4 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 

In [34]:
# working with missing data
# syntax : numpy.where(condition)
# syntax-2 : numpy.where(condition,x,y)
arr = np.array([4,400,8,None,23,45,43,324,324,3,34,324,34,23,4,None])
print("Original :",arr)
idx = np.where(arr==None,0,arr)
print(idx , type(idx))
for i in idx:
    print(i,end=' ')

Original : [4 400 8 None 23 45 43 324 324 3 34 324 34 23 4 None]
[4 400 8 0 23 45 43 324 324 3 34 324 34 23 4 0] <class 'numpy.ndarray'>
4 400 8 0 23 45 43 324 324 3 34 324 34 23 4 0 

In [36]:
# Working with missing data
# syntax : numpy.where(condition)
# syntax-2 : numpy.where(condition,x,y)
arr = np.array([4,400,8,None,23,45,43,324,324,3,34,324,34,23,4,None])
print("Original :",arr)
idx = np.extract(arr!=None,arr)
print(idx , type(idx))
for i in idx:
    print(i,end=' ')

Original : [4 400 8 None 23 45 43 324 324 3 34 324 34 23 4 None]
[4 400 8 23 45 43 324 324 3 34 324 34 23 4] <class 'numpy.ndarray'>
4 400 8 23 45 43 324 324 3 34 324 34 23 4 

In [40]:
print(np.NaN,type(np.NaN),np.nan,type(np.nan))

nan <class 'float'> nan <class 'float'>


In [46]:
# Example of np.extract()
# np.extract(condition, array)
arr = np.random.randint(2,50,20)
print(f"original : {arr}")
print("Greater than 15 :",np.extract(arr>15,arr))

original : [38 32 43 13  8 25 48 12  2 24 44 21 35 36 47 41  9 37 15  3]
Greater than 15 : [38 32 43 25 48 24 44 21 35 36 47 41 37]


In [47]:
# Example of np.extract()
# np.extract(condition, array)
arr = np.random.randint(2,50,20)
print(f"original : {arr}")
print("Lesser than 15 :",np.extract(arr<15,arr))

original : [ 7 14 41 49 34 35 20 21 34 20 49 19 31 18 47 35 42 18 44 44]
Lesser than 15 : [ 7 14]
