In [ ]:
# slicing on 1D 2D and 3D arrays

In [4]:
import numpy as np
arr = np.random.randint(12,99,12)
# print(f"Array : {arr}")
print(f"Array : {arr}")
print(f"Dimension of arr : {arr.ndim}")
print(f"Shape of arr : {arr.shape}")
print(f"Size of arr : {arr.size}")

Array : [85 43 58 24 13 33 91 75 54 63 44 62]
Dimension of arr : 1
Shape of arr : (12,)
Size of arr : 12


In [5]:
# basic slicing 
arr[::]

array([85, 43, 58, 24, 13, 33, 91, 75, 54, 63, 44, 62])

In [6]:
# reverse the array using slicing 
arr[::-1]

array([62, 44, 63, 54, 75, 91, 33, 13, 24, 58, 43, 85])

In [7]:
arr[::2]

array([85, 58, 13, 91, 54, 44])

In [8]:
arr[::-2]

array([62, 63, 75, 33, 24, 43])

In [9]:
arr[3:9] # +ve starting +ve ending

array([24, 13, 33, 91, 75, 54])

In [10]:
arr[-len(arr):5]  # -ve starting +ve ending

array([85, 43, 58, 24, 13])

In [11]:
arr[-9:8] # -ve starting +ve ending

array([24, 13, 33, 91, 75])

In [12]:
arr[-3:-9]

array([], dtype=int32)

In [13]:
arr[-3:-9:-1]

array([63, 54, 75, 91, 33, 13])

In [15]:
arr[-2:2]

array([], dtype=int32)

In [16]:
arr[2:-2]

array([58, 24, 13, 33, 91, 75, 54, 63])

In [19]:
# slicing in 2D array 
import numpy as np
arr = np.random.randint(12,99,size=(3,2))
# print(f"Array : {arr}")
print(f"Array : {arr}")
print(f"Dimension of arr : {arr.ndim}")
print(f"Shape of arr : {arr.shape}")
print(f"Size of arr : {arr.size}")

Array : [[52 70]
 [85 22]
 [29 32]]
Dimension of arr : 2
Shape of arr : (3, 2)
Size of arr : 6


In [29]:
# basic slicing on ndarray
# retrive first column
print(arr[::,0:1],arr[0:3,0:1],arr[:,0:1],arr[0:,:1],sep='\n\n')

[[52]
 [85]
 [29]]

[[52]
 [85]
 [29]]

[[52]
 [85]
 [29]]

[[52]
 [85]
 [29]]


In [36]:
# retrive last 2 rows 
print(arr[1:,:],arr[1:,::],arr[1:,0:],arr[-2:,:],arr[-2:,::],sep='\n\n')

[[85 22]
 [29 32]]

[[85 22]
 [29 32]]

[[85 22]
 [29 32]]

[[85 22]
 [29 32]]

[[85 22]
 [29 32]]


In [37]:
import numpy as np
arr = np.random.randint(12,99,size=(3,4))
# print(f"Array : {arr}")
print(f"Array : {arr}")
print(f"Dimension of arr : {arr.ndim}")
print(f"Shape of arr : {arr.shape}")
print(f"Size of arr : {arr.size}")

Array : [[88 19 85 59]
 [68 94 86 74]
 [29 46 35 89]]
Dimension of arr : 2
Shape of arr : (3, 4)
Size of arr : 12


In [45]:
arr[::2,::2],arr[0::2,:3:2]

(array([[88, 85],
        [29, 35]]),
 array([[88, 85],
        [29, 35]]))

In [49]:
arr[-3::2,-4::2],arr[-3::2,::2]

(array([[88, 85],
        [29, 35]]),
 array([[88, 85],
        [29, 35]]))

In [50]:
arr[::2,::]

array([[88, 19, 85, 59],
       [29, 46, 35, 89]])

In [51]:
arr[:2,2:]

array([[85, 59],
       [86, 74]])