In [9]:
# 2x2 indentity matrix
# identity matrix is square matrix which contains same rows x columns (3x3)

lst = [1,0,0,1]
import numpy as np
arr = np.array(lst).reshape(2,2)
print("Identity matrix :",arr)
print("Shape of matrix :",arr.shape)
print("Dimension of matrix :",arr.ndim)

Identity matrix : [[1 0]
 [0 1]]
Shape of matrix : (2, 2)
Dimension of matrix : 2


In [11]:
arr = np.array([[1,0,0],[0,1,0],[0,0,1]]).reshape(3,3)
print("Identity matrix :",arr)
print("Shape of matrix :",arr.shape)
print("Dimension of matrix :",arr.ndim)

Identity matrix : [[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape of matrix : (3, 3)
Dimension of matrix : 2


In [15]:
# syntax : numpy.identity(num,dtype)
import numpy as np
arr = np.identity(3)
print("Identity matrix :",arr)
print("Shape of matrix :",arr.shape)
print("Dimension of matrix :",arr.ndim)

Identity matrix : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of matrix : (3, 3)
Dimension of matrix : 2


In [17]:
arr = np.identity(5,dtype=int)
print("Identity matrix :",arr)
print("Shape of matrix :",arr.shape)
print("Dimension of matrix :",arr.ndim)

Identity matrix : [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Shape of matrix : (5, 5)
Dimension of matrix : 2


In [29]:
p = 1
for i in range(len(arr)):
    print(i,arr[i][i])
    p*=arr[i,i]
    # print(i,arr[i,i]) 
print(f"Product of identity matrix : {p}")

0 1
1 1
2 1
3 1
4 1
Product of identity matrix : 1


In [43]:
arr = np.identity(3,dtype=int)
print("Identity matrix :",arr)
print("Shape of matrix :",arr.shape)
print("Dimension of matrix :",arr.ndim)

Identity matrix : [[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape of matrix : (3, 3)
Dimension of matrix : 2


In [49]:
arr.shape = (9,)
print("Identity matrix :",arr)
print("Shape of matrix :",arr.shape)
print("Dimension of matrix :",arr.ndim)

Identity matrix : [1 0 0 0 1 0 0 0 1]
Shape of matrix : (9,)
Dimension of matrix : 1


In [57]:
# eye() method
# syntax : numpy.eye(n,m=none,k=none,dtype)
arr = np.eye(3,dtype = int)
print(f"Element of arr : {arr}")

Element of arr : [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [65]:
arr = np.eye(6,3,dtype=int)
print(f"Element of arr : {arr}")
print(f"Shape of matrix : {arr.shape}")
print(f"Shape of matrix : {arr.size}")
print(f"Dimension of matrix : {arr.ndim}")

Element of arr : [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape of matrix : (6, 3)
Shape of matrix : 18
Dimension of matrix : 2


In [73]:
arr = np.eye(6,3,-2,dtype=int)
print(f"Element of arr : {arr}")
print(f"Shape of matrix : {arr.shape}")
print(f"Shape of matrix : {arr.size}")
print(f"Dimension of matrix : {arr.ndim}")

Element of arr : [[0 0 0]
 [0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]
Shape of matrix : (6, 3)
Shape of matrix : 18
Dimension of matrix : 2


In [81]:
arr = np.eye(7,5,2,dtype=int)
print(f"Element of arr : {arr}")
print(f"Shape of matrix : {arr.shape}")
print(f"Shape of matrix : {arr.size}")
print(f"Dimension of matrix : {arr.ndim}")

Element of arr : [[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Shape of matrix : (7, 5)
Shape of matrix : 35
Dimension of matrix : 2
