In [ ]:
# zeros()
#syntax : var_name = numpy.zeros(shape,dtype)

In [1]:
import numpy as np 
arr = np.zeros((2,2,2))
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : float64
Size of arr : 8
Shape of arr : (2, 2, 2)
Dimension of arr : 3


In [2]:
import numpy as np 
arr = np.zeros(8,dtype=int)
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [0 0 0 0 0 0 0 0]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : int32
Size of arr : 8
Shape of arr : (8,)
Dimension of arr : 1


In [3]:
import numpy as np 
arr = np.zeros(9,dtype=int).reshape(3,3)
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [[0 0 0]
 [0 0 0]
 [0 0 0]]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : int32
Size of arr : 9
Shape of arr : (3, 3)
Dimension of arr : 2


In [4]:
# onse()
#syntax : var_name = numpy.ones(shape,dtype)
import numpy as np 
arr = np.ones((2,2,2))
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : float64
Size of arr : 8
Shape of arr : (2, 2, 2)
Dimension of arr : 3


In [5]:
arr = np.ones(9,dtype=int).reshape(3,3)
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [[1 1 1]
 [1 1 1]
 [1 1 1]]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : int32
Size of arr : 9
Shape of arr : (3, 3)
Dimension of arr : 2


In [6]:
arr = np.ones(9)
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [1. 1. 1. 1. 1. 1. 1. 1. 1.]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : float64
Size of arr : 9
Shape of arr : (9,)
Dimension of arr : 1


In [7]:
arr = np.ones(9,int)
print("Elements of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Size of arr :",arr.size)
print("Shape of arr :",arr.shape)
print("Dimension of arr :",arr.ndim)

Elements of arr : [1 1 1 1 1 1 1 1 1]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : int32
Size of arr : 9
Shape of arr : (9,)
Dimension of arr : 1


In [8]:
# full() method
# syntax : var_name = numpy.full(shape,value,dtype)
import numpy as np
arr = np.full((4,),3)
print("Element of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Shape of arr :",arr.shape)
print("Size of arr :",arr.size)
print("Dimension of arr :",arr.size)

Element of arr : [3 3 3 3]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : int32
Shape of arr : (4,)
Size of arr : 4
Dimension of arr : 4


In [9]:
arr = np.full((4,2),3)
print("Element of arr :",arr)
print("Type of arr :",type(arr))
print("Datatype of arr :",arr.dtype)
print("Shape of arr :",arr.shape)
print("Size of arr :",arr.size)
print("Dimension of arr :",arr.ndim)

Element of arr : [[3 3]
 [3 3]
 [3 3]
 [3 3]]
Type of arr : <class 'numpy.ndarray'>
Datatype of arr : int32
Shape of arr : (4, 2)
Size of arr : 8
Dimension of arr : 2
