In [3]:
# writing ndarray data into binary file
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Data :",arr)
np.save("./bfile.npy",arr)
print("File Saved.")


Data : [[1 2 3]
 [4 5 6]
 [7 8 9]]
File Saved.


In [4]:
# Reading data from binary file
fdata = np.load("./bfile.npy")
print("File Data :")
print(fdata)

File Data :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
