In [2]:
"""
    Working with files using Numpy.
    1.Text Files
    2.Binary Files
    3.JSON Files
    4.CSV Files
"""

'\n    Working with files using Numpy.\n    1.Text Files\n    2.Binary Files\n    3.JSON Files\n    4.CSV Files\n'

In [4]:
# Writing data in Text file and Reading data from File.
with open("./file.txt",'w') as fp:
    fp.write("Hello, I am Harshal Kharabe.")
    print("file Saved.")

file Saved.


In [7]:
# read data from file
try:
    with open("./file.txt","r") as fp:
        fdata = fp.read()
        print("File Data :")
        print(fdata)
        fp.close()
except Exception as e:
    print("Exception :",e)

File Data :
Hello, I am Harshal Kharabe.


In [9]:
# Writing data in Text file and Reading data from File.
with open("./file1.txt",'w') as fp:
    fp.write("1 2 3\n4 5 6\n 7 8 9")
    print("file Saved.")

file Saved.


In [10]:
# read data from file using numpy methods.
# loadtxt() is only read numeric data from file.
import numpy as np
try:
    print("Read data using numpy methods")
    data = np.loadtxt('./file1.txt')
    print("File Data :")
    print(data)
except Exception as e:
    print("Exception :",e)

Read data using numpy methods
File Data :
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [13]:
# save numpy ndarray data into file 
arr = np.array([[12.2,34.3,56.3],[1.2,2.1,3.34],[32.5,21.6,43.43]])
print("Data :",arr)
np.savetxt("./file2.txt",arr)
print("File Saved.")

Data : [[12.2  34.3  56.3 ]
 [ 1.2   2.1   3.34]
 [32.5  21.6  43.43]]
File Saved.


In [16]:
# Writing data in Text file and Reading data from File.
print("Reading data from txt file :\n",np.loadtxt("./file2.txt"))

Reading data from txt file :
 [[12.2  34.3  56.3 ]
 [ 1.2   2.1   3.34]
 [32.5  21.6  43.43]]
