In [ ]:
# choice() method

In [1]:
from numpy import random as r
import numpy as np
arr = np.array(list("PYTHON"))
ch = r.choice(arr)
print("Choice in arr :",ch)

Choice in arr : P


In [3]:
arr = np.array(list("PYTHON"))
ch = r.choice(arr)
print("Choice in arr :",ch)

Choice in arr : T


In [5]:
arr = np.array(list("PYTHON"))
ch = r.choice(arr)
print("Choice in arr :",ch)

Choice in arr : O


In [7]:
arr = np.arange(10)
ch = r.choice(arr)
print("Choice in arr :",ch)

Choice in arr : 2


In [15]:
arr = np.arange(10)
ch = r.choice(arr,size=8)
print("Choice in arr :",ch)
print("Type of choice :",type(ch))

Choice in arr : [8 3 8 5 9 4 6 3]
Type of choice : <class 'numpy.ndarray'>


In [19]:
arr = np.arange(10)
ch = r.choice(arr,size=(3,3))
print("Choice in arr :",ch)
print("Type of choice :",type(ch))
print("Dimension choice :",ch.ndim)

Choice in arr : [[7 8 7]
 [7 1 3]
 [5 1 8]]
Type of choice : <class 'numpy.ndarray'>
Dimension choice : 2


In [39]:
arr = np.array(list("123456789ncxnkdsjsqwertyuioplkjhgfdazxcvbnmLAKSJDHFGTQRWEUIOPMZNBXVC"))
ch = r.choice(arr,size=5)
ch = list(ch)
print("Caphcha code :","".join(ch))

Caphcha code : uffcB


In [41]:
arr = np.array(list("123456789ncxnkdsjsqwertyuioplkjhgfdazxcvbnmLAKSJDHFGTQRWEUIOPMZNBXVC"))
ch = r.choice(arr,size=5)
ch = list(ch)
print("Caphcha code :","".join(ch))

Caphcha code : QWd9n


In [43]:
arr = np.array(list("123456789ncxnkdsjsqwertyuioplkjhgfdazxcvbnmLAKSJDHFGTQRWEUIOPMZNBXVC"))
ch = r.choice(arr,size=5)
ch = list(ch)
print("Caphcha code :","".join(ch))

Caphcha code : 9yn1q


In [57]:
# I want 2x2 matrix number between 10,100
arr = np.arange(10,100)
matrix = r.choice(arr,size=(2,2))
print("2x2 Matrix :\n",matrix)

2x2 Matrix :
 [[22 72]
 [84 53]]


In [63]:
# I want 2x2 matrix number between 10,100
arr = np.arange(10,100)
matrix = r.choice(arr,size=(3,2,2))
print("2x2 Matrix :\n",matrix)
print("Dimension choice :",matrix.ndim)

2x2 Matrix :
 [[[40 26]
  [82 72]]

 [[12 36]
  [49 36]]

 [[78 32]
  [24 82]]]
Dimension choice : 3
