In [ ]:
# randint()
# syntax : var_name = numpy.random.randint(10)
# it gives any one random number between 0 to 9

In [1]:
from numpy import random as r

In [3]:
val = r.randint(10)
print(f"Random value : {val}")

Random value : 2


In [5]:
val = r.randint(100)
print(f"Random value : {val}")

Random value : 98


In [7]:
val = r.randint(10)
print(f"Random value : {val}")

Random value : 5


In [9]:
val = r.randint(10)
print(f"Random value : {val}")

Random value : 2


In [11]:
val = r.randint(10,100)
print(f"Random value : {val}")

Random value : 54


In [15]:
val = r.randint(10,100)
print(f"Random value : {val}")

Random value : 82


In [ ]:
# 4 digit OTP generation using randint
val = r.randint(1000,100)
print(f"Random value : {val}")

In [35]:
val = r.randint(10,100,size=12)
print(f"Random value : {val} \nType of val is {type(val)}")

Random value : [30 32 50 21 75 12 57 15 72 29 99 39] 
Type of val is <class 'numpy.ndarray'>


In [37]:
val = r.randint(10,100,size=12).reshape(2,6)
print(f"Random value : {val} \nType of val is {type(val)}")
print(f"Dimension of arr is {val.ndim}")
print(f"Size of arr is {val.size}")
print(f"Shape of arr is {val.shape}")

Random value : [[80 35 17 44 50 89]
 [32 90 93 33 67 31]] 
Type of val is <class 'numpy.ndarray'>
Dimension of arr is 2
Size of arr is 12
Shape of arr is (2, 6)


In [39]:
val = r.randint(10,100,size=32).reshape(2,2,2,2,2)
print(f"Random value : {val} \nType of val is {type(val)}")
print(f"Dimension of arr is {val.ndim}")
print(f"Size of arr is {val.size}")
print(f"Shape of arr is {val.shape}")

Random value : [[[[[92 21]
    [22 86]]

   [[52 97]
    [44 45]]]


  [[[52 72]
    [96 61]]

   [[42 42]
    [69 23]]]]



 [[[[72 21]
    [34 86]]

   [[51 21]
    [21 48]]]


  [[[47 81]
    [14 24]]

   [[53 65]
    [71 12]]]]] 
Type of val is <class 'numpy.ndarray'>
Dimension of arr is 5
Size of arr is 32
Shape of arr is (2, 2, 2, 2, 2)


In [43]:
val = r.randint(10,100,size=2*6*3).reshape(2,6,3)
print(f"Random value : {val} \nType of val is {type(val)}")
print(f"Dimension of arr is {val.ndim}")
print(f"Size of arr is {val.size}")
print(f"Shape of arr is {val.shape}")

Random value : [[[43 63 73]
  [96 51 62]
  [35 17 27]
  [10 35 26]
  [20 53 30]
  [85 27 43]]

 [[15 96 61]
  [40 36 22]
  [60 39 45]
  [72 73 83]
  [52 36 10]
  [86 41 19]]] 
Type of val is <class 'numpy.ndarray'>
Dimension of arr is 3
Size of arr is 36
Shape of arr is (2, 6, 3)
