In [ ]:
# rand() method
# syntax : numpy.random.rand()
# used to generate random float numbers.

In [30]:
from numpy import random as r
arr = r.randint(1.0,2.5) # randint only support integer numbers.
print(arr)

1


In [72]:
from numpy import random as r
arr = r.rand() # rand only generate single float numbers between 0.0 to 1.0 both will not include
print("Random float value :",arr)

Random float value : 0.40474175217916264


In [70]:
arr = r.rand() # rand only generate single float numbers between 0.0 to 1.0 both will not include
print("Random float value :",round(arr,3))

Random float value : 0.405


In [74]:
arr = r.rand() # rand only generate single float numbers between 0.0 to 1.0 both will not include
print("Random float value :",arr)

Random float value : 0.9872882034731824


In [64]:
# syntax : arr = numpy.random.rand(value)
arr = r.rand(3) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Size of arr :",arr.size)

[0.4821727  0.09576162 0.78394626] <class 'numpy.ndarray'>
Dimension of arr : 1
Size of arr : 3


In [62]:
# syntax : arr = numpy.random.rand(rows,cols)
arr = r.rand(3,3) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Size of arr :",arr.size)

[[0.00623503 0.22148836 0.11026748]
 [0.14900453 0.76608575 0.01743953]
 [0.2478816  0.59539922 0.39292592]] <class 'numpy.ndarray'>
Dimension of arr : 2
Size of arr : 9


In [60]:
# syntax : arr = numpy.random.rand(rows,cols)
arr = r.rand(5,6) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Size of arr :",arr.size)

[[0.25548726 0.09451096 0.83375125 0.27826583 0.78470018 0.83619418]
 [0.40762592 0.88342325 0.389051   0.58495451 0.96205281 0.59705148]
 [0.94699606 0.34692993 0.61042938 0.83951166 0.30090955 0.29847891]
 [0.67482448 0.12943123 0.50978534 0.93248093 0.2434716  0.77470855]
 [0.33402019 0.04746496 0.85442017 0.0092849  0.46293841 0.19549779]] <class 'numpy.ndarray'>
Dimension of arr : 2
Size of arr : 30


In [66]:
# syntax : arr = numpy.random.rand(no.of.matrix,rows,cols)
arr = r.rand(2,3,3) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Size of arr :",arr.size)

[[[0.66994054 0.18826088 0.29322739]
  [0.766958   0.68881565 0.36160513]
  [0.84339288 0.53970986 0.96997733]]

 [[0.16237721 0.05419397 0.13047253]
  [0.67874156 0.28641139 0.0538013 ]
  [0.51904038 0.07795482 0.96389929]]] <class 'numpy.ndarray'>
Dimension of arr : 3
Size of arr : 18


In [76]:
# syntax : arr = numpy.random.rand(no.of.matrix,rows,cols)
arr = r.rand(3,2,3) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Dimension of arr :",arr.size)

[[[0.60324592 0.65071766 0.27717907]
  [0.19630387 0.86106318 0.51108874]]

 [[0.44070775 0.20795993 0.26357326]
  [0.81793572 0.24865955 0.88889634]]

 [[0.71379968 0.24096162 0.29677569]
  [0.74222343 0.45126741 0.36646191]]] <class 'numpy.ndarray'>
Dimension of arr : 3
Dimension of arr : 18


In [86]:
arr = r.rand(8)
print("Values in arr :")
for i in arr:
    print(round(i,2),end=' ')

Values in arr :
0.47 0.92 0.52 0.92 0.9 0.72 0.35 0.83 

In [96]:
# syntax : arr = numpy.random.rand(rows,cols)
arr = r.rand(4,3) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Dimension of arr :",arr.size)
print("-------------------------------------------")
for row in range(len(arr)):
    for col in range(len(arr[0])):
        print(round(arr[row,col],3),end=' ')
    print()

[[6.78962642e-04 5.96808092e-02 9.74921071e-01]
 [5.91573531e-02 5.96357636e-03 3.25456010e-01]
 [2.44100526e-01 6.92087432e-02 1.82607289e-01]
 [7.23129437e-01 1.56085159e-01 1.38827523e-01]] <class 'numpy.ndarray'>
Dimension of arr : 2
Dimension of arr : 12
-------------------------------------------
0.001 0.06 0.975 
0.059 0.006 0.325 
0.244 0.069 0.183 
0.723 0.156 0.139 


In [116]:
arr = r.rand(3,4,3) # rand generates float numbers value times between 0.0 to 1.0
print(arr,type(arr))
print("Dimension of arr :",arr.ndim)
print("Dimension of arr :",arr.size)
print("-------------------------------------------")
for matrix in range(len(arr)):
    for row in range(len(arr[0])):
        for col in range(len(arr[0,0])):
            print(round(arr[matrix,row,col],3),"--",end=' ')
        print()
    print()

[[[0.26690665 0.88664896 0.65720862]
  [0.03038526 0.26219987 0.29728339]
  [0.80330952 0.54141711 0.17228164]
  [0.49170499 0.57356619 0.52011041]]

 [[0.68014806 0.37853087 0.12068008]
  [0.9772859  0.0510087  0.48770124]
  [0.31254911 0.07814658 0.01487179]
  [0.43423297 0.04606448 0.88295808]]

 [[0.99251165 0.48952633 0.02556288]
  [0.33492204 0.84547959 0.85730974]
  [0.13968023 0.40264261 0.20150787]
  [0.63776055 0.90834833 0.30278781]]] <class 'numpy.ndarray'>
Dimension of arr : 3
Dimension of arr : 36
-------------------------------------------
0.267 -- 0.887 -- 0.657 -- 
0.03 -- 0.262 -- 0.297 -- 
0.803 -- 0.541 -- 0.172 -- 
0.492 -- 0.574 -- 0.52 -- 

0.68 -- 0.379 -- 0.121 -- 
0.977 -- 0.051 -- 0.488 -- 
0.313 -- 0.078 -- 0.015 -- 
0.434 -- 0.046 -- 0.883 -- 

0.993 -- 0.49 -- 0.026 -- 
0.335 -- 0.845 -- 0.857 -- 
0.14 -- 0.403 -- 0.202 -- 
0.638 -- 0.908 -- 0.303 -- 

