In [ ]:
# randn() method
# randn() generate any floating point number between any positive or negative numbers.
# syntax : numpy.random.randn() 

In [1]:
from numpy import random as r
val = r.randn()
print("Random value :",val)

Random value : -1.1415410795228382


In [3]:
val = r.randn()
print("Random value :",val)

Random value : 1.9025403696256151


In [9]:
# syntax : val = numpy.random.randn(number) -- number is 3 then it generate 3 positive or negative random value
val = r.randn(3)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [0.59121674 0.96415015 0.09541568]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 1


In [11]:
val = r.randn(8)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [-0.05710819 -0.80068328 -1.28870323 -0.45289128  1.44255159  2.20497737
 -0.22008853  0.1890448 ]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 1


In [17]:
# syntax : arr = r.randn(rows,cols)
val = r.randn(4,5)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [[ 0.38161655 -0.70681101  0.66978571  1.57476808 -0.28297913]
 [ 0.99133741  1.73197901  0.98692594  0.66170205  1.08117707]
 [ 2.02967855  2.3817548  -0.04875395 -1.05502942 -0.67834636]
 [-1.64691894 -1.11361022  0.14256503 -1.06010689  0.6326731 ]]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 2


In [19]:
# syntax : arr = r.randn(rows,cols)
val = r.randn(8,5)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [[ 2.75354769  0.43921644  1.23260741 -1.80992409 -0.78463286]
 [-1.45901759  1.2448724  -0.42933962  1.23444754  0.78897797]
 [ 1.03541212  0.59487575  0.8603334   0.5394352  -0.2155535 ]
 [ 0.24949889  0.03826265  1.46671135 -0.35896051 -0.71458833]
 [ 0.22190462 -1.63053283 -0.85785777  0.55931356  0.21003243]
 [ 0.42633564 -0.76804971  0.98034821 -0.41697401  0.02387962]
 [-1.04766268  0.70545732 -1.15348527 -0.65401758 -0.55599036]
 [-0.54316855  1.92370411  1.04372664 -2.01691201  0.04362439]]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 2


In [21]:
# syntax : arr = r.randn(no.of.matrics,rows,cols)
val = r.randn(4,2,5)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [[[ 0.10441683 -0.87199094 -0.52976388  0.45610173 -0.65148368]
  [ 0.17786545  0.88961877 -1.835957   -0.03363171  0.17946114]]

 [[ 1.88717452 -0.42540685 -0.62648831 -0.97653857  0.92419842]
  [-1.02621613  0.83467788  2.12683452 -0.92572606 -0.84705435]]

 [[ 0.4705183   0.17233065  0.32101332  0.68588501  0.31405978]
  [-0.4614326  -0.44010071  0.36979499 -0.03894276  1.32520332]]

 [[ 0.66630338  0.10767212 -0.46073303 -0.38240407  1.21227821]
  [ 0.10704123  0.34937507  0.30673686 -0.36751012  0.82717647]]]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 3


In [39]:
# syntax : arr = r.randn(no.of.matrics,rows,cols)
val = r.randn(3,2,2)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)
print("---------------------------------------")
for i in range(len(val)):
    for j in range(len(val[0])):
        for k in range(len(val[0,0])):
                print(round(val[i,j,k],3),end=' -- ')
        print()
    print()

Random value : [[[-0.80426287 -0.73025654]
  [ 0.88583768 -0.24955525]]

 [[ 1.18214122 -1.08555511]
  [ 0.43857275  1.26442146]]

 [[-0.52352952  0.94928995]
  [-0.44984958  1.73133971]]]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 3
---------------------------------------
-0.804 -- -0.73 -- 
0.886 -- -0.25 -- 

1.182 -- -1.086 -- 
0.439 -- 1.264 -- 

-0.524 -- 0.949 -- 
-0.45 -- 1.731 -- 



In [27]:
# syntax : arr = r.randn(cluster,no.of.matrics,rows,cols)
val = r.randn(2,2,2,2)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [[[[-1.19246156 -0.87791287]
   [-1.22295845  0.12992055]]

  [[ 0.75870745  0.71539676]
   [ 0.92224581  0.91196154]]]


 [[[-0.01678692  0.37653134]
   [-0.48359337  1.49347408]]

  [[ 1.79940941 -0.84814498]
   [-0.04483064  1.49329665]]]]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 4


In [33]:
# syntax : arr = r.randn(no.of.matrics,rows,cols)
val = r.randn(4,2)
print("Random value :",val)
print("Type of arr :",type(val))
print("Dimension of arr :",val.ndim)

Random value : [[-2.69729534 -0.3176783 ]
 [-0.18030947 -0.94368722]
 [ 0.46484755 -0.78371865]
 [-0.6476897   0.89547401]]
Type of arr : <class 'numpy.ndarray'>
Dimension of arr : 2


In [ ]:
# normal() method
# syntax : np.random.normal()
# Generate a single random number
# Use a mean (center) of 0
# Use a standard deviation of 1

In [43]:
from numpy import random as r
arr = r.normal() # --> mean is 0 and standard deviation id 1
print(arr)

0.7403632756223247


In [49]:
arr = r.normal() # --> mean is 0 and standard deviation id 1
print("Random value :",arr,type(arr))

Random value : 0.34649410124177676 <class 'float'>


In [51]:
arr = r.normal() # --> mean is 0 and standard deviation id 1
print("Random value :",arr,type(arr))

Random value : 0.37759276056179697 <class 'float'>


In [ ]:
# syntax : np.random.nprmal(loc=0,scale=1,size=None)
# loc = mean (center of the distribution)
# scale = standard deviation (spread of the distribution)
# size = number of values to generate

In [108]:
from numpy import random as r
arr = r.normal(4,5,100)
print(arr)
m = numpy.mean(arr)
s = numpy.std(arr)
print("Mean :",m)
print("Stander Deviation :",s)

[ 2.94381237 -3.62000967  8.05273474 -3.64858049 -3.05437407 -6.56430043
  5.22418148  1.43245855  5.94445972  8.50950234 -2.39457864  9.22116039
  1.74564283  8.11281005 10.27537671 10.89582119  4.24090933  9.09883301
  7.53581586  2.8382713  12.41547851  7.13685545 -0.39172994  6.78415973
 -3.71434307  2.55082823 12.65745949 10.23617089  7.15002725 -5.23409563
 12.04889837  9.77102326  2.4484065   1.28589654  1.917916    8.23527722
  4.91543801  6.49650696  0.62688735  0.69911466  2.81284818  5.72062119
  3.97942027 -2.37768248  6.7703298  -1.59638036 12.29368079 -4.3136429
 -1.77930861 -3.69315819 -4.16268489 -0.43761947 -0.67303096 -0.52722245
  2.88465313 -0.18258743  7.39810684  8.55788474  3.46753962  1.77618542
  4.20278246  0.14121365 -9.41272713  3.4118019  -4.80946975 11.86127292
  4.5183169  -2.30216058  1.8835085   3.45030361 11.16893341  7.67828029
  5.89301398  2.66481101  4.97109277  4.06634793  6.35923951 11.03029744
  2.34537837  3.68398734  6.46573644 10.50849156  6.

In [112]:
from numpy import random as r
arr = r.normal(5,5,size=(3,3,4))
print(arr)
m = numpy.mean(arr)
s = numpy.std(arr)
print("Mean :",m)
print("Stander Deviation :",s)
print()

[[[-4.36349802e+00  1.03485937e+01  3.36181141e+00  7.93707826e+00]
  [ 7.87758775e-01  3.13134984e+00  9.53218898e+00  4.29408803e+00]
  [ 4.81172956e+00  4.11489737e+00  1.91545045e-01  1.10895960e+01]]

 [[ 9.05532265e+00  4.53394854e+00  1.21365558e+01 -3.38296176e+00]
  [ 7.13062316e+00  3.92842462e-01  5.83036743e+00  4.50995083e-03]
  [-1.61122824e+00  4.70574455e+00  3.07400299e+00  1.32373923e+01]]

 [[ 2.90116896e+00 -1.01720555e-01  4.15532711e+00  1.20678091e+01]
  [ 1.09402120e+01 -1.47117911e+00 -5.17371513e+00  1.17835455e+01]
  [ 1.44272515e+00  6.76135980e+00  7.15202235e-01  6.88735721e-01]]]
Mean : 4.307048042217863
Stander Deviation : 4.940551659787564


In [ ]:
from numpy import random as r
arr = r.normal(4,5,100)
print(arr)
m = numpy.mean(arr)
s = numpy.std(arr)
print("Mean :",m)
print("Stander Deviation :",s)