In [ ]:
# shuffle() method
# syntax : numpy.random.shuffle(ndarrayobject)

In [15]:
from numpy import random as r
import numpy as np
arr = np.arange(10,dtype=int)
print("Unshuffle : ",arr,id(arr))

r.shuffle(arr)
print("Shuffle : ",arr,id(arr))

Unshuffle :  [0 1 2 3 4 5 6 7 8 9] 2736921837072
Shuffle :  [2 1 8 5 3 7 9 4 0 6] 2736921837072


In [17]:
arr = np.arange(10,dtype=int)
print("Unshuffle : ",arr,id(arr))
r.shuffle(arr)
print("Shuffle : ",arr,id(arr))

Unshuffle :  [0 1 2 3 4 5 6 7 8 9] 2736907880368
Shuffle :  [1 3 9 2 7 5 8 0 4 6] 2736907880368


In [19]:
arr = np.arange(10,dtype=int)
print("Unshuffle : ",arr)
r.shuffle(arr)
print("Shuffle : ",arr)

for i in range(1,len(arr)+1):
    r.shuffle(arr)
    print(f"Combination {i} --> {arr}")

Unshuffle :  [0 1 2 3 4 5 6 7 8 9]
Shuffle :  [3 1 0 9 2 7 6 8 5 4]
Combination 1 --> [0 6 9 7 5 4 1 8 2 3]
Combination 2 --> [9 8 4 1 7 0 6 5 2 3]
Combination 3 --> [2 0 8 4 1 9 7 3 6 5]
Combination 4 --> [2 7 9 0 6 1 5 8 3 4]
Combination 5 --> [4 3 0 5 2 8 7 1 6 9]
Combination 6 --> [1 7 9 5 6 2 3 0 8 4]
Combination 7 --> [1 6 2 0 5 7 4 9 8 3]
Combination 8 --> [3 2 9 5 8 7 6 1 4 0]
Combination 9 --> [4 5 1 9 0 8 7 2 3 6]
Combination 10 --> [9 3 5 8 7 6 0 4 1 2]


In [35]:
# show the no.of.rearrangement values of "MISSISSIPPI"
s = "MISSISSIPPI"
arr = np.array(list(s))
for i in range(1,6):
    r.shuffle(arr)
    print(f"{i} Rearrangement of 'MISSISSIPPI' : {"".join(arr)}")

1 Rearrangement of 'MISSISSIPPI' : IPMIIIPSSSS
2 Rearrangement of 'MISSISSIPPI' : IISMIPSIPSS
3 Rearrangement of 'MISSISSIPPI' : SSMPSSIPIII
4 Rearrangement of 'MISSISSIPPI' : PSISSIMPIIS
5 Rearrangement of 'MISSISSIPPI' : IPPSSISMIIS


In [43]:
# Shufffleing of 2D matrix
# in 2D rows will shuffled.
arr = r.randint(1,101,size=(6,5))
print("Original array :",arr)
r.shuffle(arr)
print("Shuffle array :",arr)

Original array : [[79 28 85 14  8]
 [34 60 42 36 57]
 [84 93 24 97 82]
 [85 43 13 83  2]
 [21 59 99 89 59]
 [74 74  1 56 11]]
Shuffle array : [[85 43 13 83  2]
 [84 93 24 97 82]
 [74 74  1 56 11]
 [21 59 99 89 59]
 [79 28 85 14  8]
 [34 60 42 36 57]]


In [45]:
# Shufffleing of 2D matrix
# in 2D rows will shuffled.
arr = r.randint(1,101,size=(6,5))
print("Original array :",arr)
r.shuffle(arr)
print("Shuffle array :",arr)

Original array : [[32 57 32 95 13]
 [ 2 62 37 70 31]
 [75 47 65 78 64]
 [32  2 47 93  1]
 [23 82 18 68 36]
 [31 64 56 43 65]]
Shuffle array : [[75 47 65 78 64]
 [31 64 56 43 65]
 [32 57 32 95 13]
 [32  2 47 93  1]
 [23 82 18 68 36]
 [ 2 62 37 70 31]]


In [49]:
# Shufffleing of #3D matrix
# in 3D matrix will shuffled.
arr = r.randint(1,101,size=(2,6,5))
print("Original array :",arr)
r.shuffle(arr)
print("Shuffle array :",arr)
r.shuffle(arr)
print("Shuffle array :",arr)

Original array : [[[20  9 45 10 99]
  [70 78 41 24 33]
  [72 29 51 12 99]
  [14 31 12  6 25]
  [52 28 84 64 34]
  [52 29 97  5 71]]

 [[47 96 12 77 94]
  [92 28 79 66 69]
  [94 81 41 51 54]
  [86 30 47 19 92]
  [42  9 62 54 88]
  [41 57 88 82 52]]]
Shuffle array : [[[47 96 12 77 94]
  [92 28 79 66 69]
  [94 81 41 51 54]
  [86 30 47 19 92]
  [42  9 62 54 88]
  [41 57 88 82 52]]

 [[20  9 45 10 99]
  [70 78 41 24 33]
  [72 29 51 12 99]
  [14 31 12  6 25]
  [52 28 84 64 34]
  [52 29 97  5 71]]]
Shuffle array : [[[20  9 45 10 99]
  [70 78 41 24 33]
  [72 29 51 12 99]
  [14 31 12  6 25]
  [52 28 84 64 34]
  [52 29 97  5 71]]

 [[47 96 12 77 94]
  [92 28 79 66 69]
  [94 81 41 51 54]
  [86 30 47 19 92]
  [42  9 62 54 88]
  [41 57 88 82 52]]]


In [53]:
# Another method for rearrangement of array
# permutation() method
# syntax : var = numpy.random.permutation(ndarrayobject)
# difference between both shuffle & permutation is 
# -- Permutation store the shuffle array in a variable and shuffle not stored array.

arr = np.array([1,2,3,45,6,7,89,10])
print("Original :",arr)
l1 = r.permutation(arr)
print("Shuffled :",l1)



Original : [ 1  2  3 45  6  7 89 10]
Shuffled : [89  6  2  3 10 45  7  1]


In [63]:
# find all possible permutations of list
l1 = [1,2,3] 
import itertools as it
prem = it.permutations(l1)
l1 = list(prem)
for i in l1:
    print(i)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [69]:
# find all possible permutations of list need no.of.combinations.
l1 = [1,2,3] 
import itertools as it
c = 2
prem = it.permutations(l1,c)
l1 = list(prem)
for i in l1:
    print(i)

(1, 2)
(1, 3)
(2, 1)
(2, 3)
(3, 1)
(3, 2)


In [81]:
# find all possible permutations of list need no.of.combinations.
l1 = [1,2,3] 
import itertools as it
arr=[]
for i in range(1,len(l1)+1):
    prem = it.permutations(l1,i)
    print(prem)
    arr.extend(list(prem))
print(arr)

[(1,), (2,), (3,), (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2), (1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [85]:
# permutation of numpy array

arr = np.array([10,20,30])
print(arr)
prem = list(it.permutations(arr))
print(prem)
for i in prem:

[10 20 30]
[(10, 20, 30), (10, 30, 20), (20, 10, 30), (20, 30, 10), (30, 10, 20), (30, 20, 10)]
