In [ ]:
# uniform() method
# syntax : numpy.random.uniform()
# similar to the rand() but slightly different.

In [1]:
from numpy import random as r
val = r.uniform()
print(val,type(val))

0.7054371782000337 <class 'float'>


In [3]:
val = r.uniform()
print(val,type(val))

0.4249127333462118 <class 'float'>


In [9]:
# syntax : numpy.random.uniform(low,high)
val = r.uniform(12,13)
print(val,type(val))

12.599449647789047 <class 'float'>


In [11]:
# syntax : numpy.random.uniform(high,low)
val = r.uniform(12,13)
print(val,type(val))

12.462231579923447 <class 'float'>


In [13]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,13,size=8)
print(val,type(val))

[12.89548778 12.92436319 12.56431095 12.4546055  12.29855123 12.71496174
 12.45703427 12.13202794] <class 'numpy.ndarray'>


In [15]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,13,size=16)
print(val,type(val))

[12.5625214  12.66174287 12.2487413  12.58322922 12.87510563 12.07147817
 12.02174275 12.55627376 12.90595952 12.9385851  12.33535407 12.42345347
 12.38074339 12.35217161 12.53491587 12.06501223] <class 'numpy.ndarray'>


In [17]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,23,size=8)
print(val,type(val))

[14.38664838 22.30044207 20.70878131 16.27883728 17.19069006 20.34122399
 17.37884949 21.95588026] <class 'numpy.ndarray'>


In [21]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,13,size=(3,3))
print(val,type(val))
print("Size of arr : ",val.size)
print("Dimension of arr : ",val.ndim)

[[12.86897604 12.20851183 12.49100791]
 [12.29523161 12.96558749 12.27908345]
 [12.66556549 12.99307734 12.95288888]] <class 'numpy.ndarray'>
Size of arr :  9
Dimension of arr :  2


In [23]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,13,size=(8,3))
print(val,type(val))
print("Size of arr : ",val.size)
print("Dimension of arr : ",val.ndim)

[[12.72767369 12.62799988 12.74589842]
 [12.49814813 12.27007913 12.98270949]
 [12.65082034 12.90493479 12.54554977]
 [12.67523265 12.80208426 12.85270682]
 [12.62539437 12.88982162 12.24764233]
 [12.38636136 12.83331096 12.06537974]
 [12.26043814 12.69746223 12.4251362 ]
 [12.39076683 12.69833475 12.67293689]] <class 'numpy.ndarray'>
Size of arr :  24
Dimension of arr :  2


In [25]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,13,size=(4,3,3))
print(val,type(val))
print("Size of arr : ",val.size)
print("Dimension of arr : ",val.ndim)

[[[12.70448894 12.48085315 12.27850808]
  [12.57219098 12.70139285 12.72159733]
  [12.1289539  12.64684146 12.55459359]]

 [[12.3216275  12.67314714 12.71478545]
  [12.28864055 12.90820903 12.92410313]
  [12.49374173 12.79618676 12.69029949]]

 [[12.44170604 12.79002497 12.18983677]
  [12.41099876 12.01652497 12.33960977]
  [12.72723196 12.84046208 12.67207977]]

 [[12.38818005 12.90835321 12.15680752]
  [12.00719831 12.75313641 12.91317996]
  [12.88424621 12.14651461 12.21482431]]] <class 'numpy.ndarray'>
Size of arr :  36
Dimension of arr :  3


In [27]:
# syntax : numpy.random.uniform(low,high,size=value)
val = r.uniform(12,13,size=(2,2,3,3))
print(val,type(val))
print("Size of arr : ",val.size)
print("Dimension of arr : ",val.ndim)

[[[[12.1534286  12.76398859 12.00519428]
   [12.42510574 12.09486666 12.91960139]
   [12.63567733 12.62475545 12.61036726]]

  [[12.89450549 12.57948732 12.52294766]
   [12.02496064 12.6321383  12.77181041]
   [12.69069294 12.3921564  12.51893643]]]


 [[[12.34255677 12.44449201 12.88634644]
   [12.34963579 12.08309785 12.1707835 ]
   [12.15346497 12.12528785 12.26026619]]

  [[12.48902969 12.41169997 12.23191665]
   [12.24124475 12.96020046 12.03481741]
   [12.66279754 12.90051798 12.33438542]]]] <class 'numpy.ndarray'>
Size of arr :  36
Dimension of arr :  4
