In [1]:
import numpy as np
from numpy import random as r
arr = r.randint(2,90,size=20)
print(arr)
print("Max : ",np.amax(arr))
print("Min : ",np.amin(arr))

[25 31 28 79 57 10  2 10 85 30 12 14 79 55 26 33 27  9 49 38]
Max :  85
Min :  2


In [2]:
import numpy as np
from numpy import random as r
arr = r.randint(2,90,size=(3,4))
print(arr)
print("Max : ",np.amax(arr))
print("Min : ",np.amin(arr))
print("Column Wise Max : ",np.amax(arr,axis=0)) # return maxium value in each column
print("Row Wise Max : ",np.amax(arr,axis=1)) # return maxium value in each row
print("Column Wise Min : ",np.amax(arr,axis=0)) # return minium value in each column
print("Row Wise Min : ",np.amin(arr,axis=1)) # return minium value in each row

[[38 72  3 23]
 [11 69 75 76]
 [67 13 36 59]]
Max :  76
Min :  3
Column Wise Max :  [67 72 75 76]
Row Wise Max :  [72 76 67]
Column Wise Min :  [67 72 75 76]
Row Wise Min :  [ 3 11 13]


In [16]:
import numpy as np
from numpy import random as r
arr = r.randint(2,90,size=(3,4))
print(arr)
print("Max : ",np.amax(arr))
print("Min : ",np.amin(arr))
print("Column Wise Max : ",np.amax(arr,axis=0)) # return maxium value in each column
print("Row Wise Max : ",np.amax(arr,axis=1)) # return maxium value in each row
print("Column Wise Min : ",np.amax(arr,axis=0)) # return minium value in each column
print("Row Wise Min : ",np.amin(arr,axis=1)) # return minium value in each row

[[81 27 61 78]
 [42 81 31 15]
 [ 8 23 50 48]]
Max :  81
Min :  8
Column Wise Max :  [81 81 61 78]
Row Wise Max :  [81 81 50]
Column Wise Min :  [81 81 61 78]
Row Wise Min :  [27 15  8]


In [7]:
arr = r.randint(2,99,size=(4,5))
print(arr)
print("Max in matrix :",np.amax(arr))
print("Min in matrix :",np.amin(arr))
colmax = np.amax(arr,axis=0)
rowmax = np.amax(arr,axis=1)
rowmin = np.amin(arr,axis=0)
colmin = np.amin(arr,axis=1)
print("Column max : ",colmax)
print("Column min : ",colmin)
print("Row min : ",rowmin)
print("Row max : ",rowmax)

[[64 35 25 59 38]
 [79 86 58 91 33]
 [55  5 50 45 34]
 [48 93 34 56 81]]
Max in matrix : 93
Min in matrix : 5
Column max :  [79 93 58 91 81]
Column min :  [25 33  5 34]
Row min :  [48  5 25 45 33]
Row max :  [64 91 55 93]
