In [6]:
import numpy as np
from numpy import random as r
arr = r.randint(2,90,size=20)
print(arr)
print("Max : ",np.amax(arr))
print("Min : ",np.amin(arr))

[23 53 79  3 86 24 42 44 37 17 57  2 86 41  8 24 86 53 18 75]
Max :  86
Min :  2


In [13]:
import numpy as np
from numpy import random as r
arr = r.randint(2,90,size=(3,4))
print(arr)
print("Max : ",np.amax(arr))
print("Min : ",np.amin(arr))
print("Column Wise Max : ",np.amax(arr,axis=0)) # return maxium value in each column
print("Row Wise Max : ",np.amax(arr,axis=1)) # return maxium value in each row
print("Column Wise Min : ",np.amax(arr,axis=0)) # return minium value in each column
print("Row Wise Min : ",np.amin(arr,axis=1)) # return minium value in each row

[[37 75 42 35]
 [25 18 22 63]
 [80 79 72 10]]
Max :  80
Min :  10
Column Wise Max :  [80 79 72 63]
Row Wise Max :  [75 63 80]
Column Wise Min :  [80 79 72 63]
Row Wise Min :  [35 18 10]


In [16]:
import numpy as np
from numpy import random as r
arr = r.randint(2,90,size=(3,4))
print(arr)
print("Max : ",np.amax(arr))
print("Min : ",np.amin(arr))
print("Column Wise Max : ",np.amax(arr,axis=0)) # return maxium value in each column
print("Row Wise Max : ",np.amax(arr,axis=1)) # return maxium value in each row
print("Column Wise Min : ",np.amax(arr,axis=0)) # return minium value in each column
print("Row Wise Min : ",np.amin(arr,axis=1)) # return minium value in each row

[[81 27 61 78]
 [42 81 31 15]
 [ 8 23 50 48]]
Max :  81
Min :  8
Column Wise Max :  [81 81 61 78]
Row Wise Max :  [81 81 50]
Column Wise Min :  [81 81 61 78]
Row Wise Min :  [27 15  8]
