In [1]:
import numpy as np

In [5]:
# mean()

arr = np.array([12,34,56,56,65,65,6])
print("Mean :",np.mean(arr))  # Output: 41.8

Mean : 42.0


In [4]:
# without mean()
def find_mean(nums):
    return sum(nums)/len(nums)

# find median without mean()
print("Without mean() :",find_mean(arr))

Without mean() : 42.0


In [9]:
# mean of a column

arr = np.array([12,34,32,21,56,78]).reshape(3,2)
print(arr)
print(arr.mean(axis=1))  # axis=1 means along rows
print(arr.mean(axis=0))  # axis=1 means along rows

[[12 34]
 [32 21]
 [56 78]]
[23.  26.5 67. ]
[33.33333333 44.33333333]


In [ ]:
# median()

In [15]:
arr = np.array([12,82,3,5,33,33,35,67,])
m = np.median(arr)
print("Median :",m)

Median : 33.0


In [22]:
arr = np.array([2,32,45,90,56,7,77,12,34,4,5,7,757,5,745,634,542,24,5,43,]).reshape(5,4)
print(arr)
print("Row wise median :",np.median(arr,axis=1))
print("Col wise median :",np.median(arr,axis=0))

[[  2  32  45  90]
 [ 56   7  77  12]
 [ 34   4   5   7]
 [757   5 745 634]
 [542  24   5  43]]
Row wise median : [ 38.5  34.    6.  689.5  33.5]
Col wise median : [56.  7. 45. 43.]


In [23]:
# variance()

arr = np.array([12,21,2,3,23,24,45,4])
print(arr)
print("Variance :",np.var(arr))

[12 21  2  3 23 24 45  4]
Variance : 187.4375


In [27]:
# variance()

arr = np.array([12,21,2,3,23,24,45,4]).reshape(4,2)
print(arr)
print("Col Variance :",np.var(arr,axis=0))
print("Row Variance :",np.var(arr,axis=1))

[[12 21]
 [ 2  3]
 [23 24]
 [45  4]]
Col Variance : [255.25  91.5 ]
Row Variance : [2.0250e+01 2.5000e-01 2.5000e-01 4.2025e+02]


In [28]:
# variance()

arr = np.arange(5*6).reshape(6,5)
print(arr)
print("Col Variance :",np.var(arr,axis=0))
print("Row Variance :",np.var(arr,axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Col Variance : [72.91666667 72.91666667 72.91666667 72.91666667 72.91666667]
Row Variance : [2. 2. 2. 2. 2. 2.]


In [32]:
# stander_deviation()

arr = np.array([12,21,2,3,23,24,45,4])
print(arr)
print("Stander deviation :",np.std(arr))

[12 21  2  3 23 24 45  4]
Stander deviation : 13.690781570093067


In [33]:
# stander_deviation()

arr = np.array([12,21,2,3,23,24,45,4]).reshape(4,2)
print(arr)
print("Col std :",np.std(arr,axis=0))
print("Row std :",np.std(arr,axis=1))

[[12 21]
 [ 2  3]
 [23 24]
 [45  4]]
Col std : [15.97654531  9.56556323]
Row std : [ 4.5  0.5  0.5 20.5]


In [36]:
# mode()
import statistics as s
arr = np.array([12,21,2,3,23,24,45,4])
print(arr)
print("Mode :",s.mode(arr))

[12 21  2  3 23 24 45  4]
Mode : 12


In [38]:
# mode()
import statistics as s
arr = np.array([1,1,1,3,3,3,2,2,2,8])
print(arr)
print("Mode :",s.mode(arr))
print("MultiMode :",s.multimode(arr))

[1 1 1 3 3 3 2 2 2 8]
Mode : 1
MultiMode : [1, 3, 2]
