In [2]:
import numpy as np

In [3]:
arr = np.array([23,4,34,34,3,435,3,55,4])
print("Original :",arr)
arr = np.sort(arr)
print("sorted :",arr)

Original : [ 23   4  34  34   3 435   3  55   4]
sorted : [  3   3   4   4  23  34  34  55 435]


In [7]:
arr = np.array([23,4,34,34,3,435,3,55,4])
print("Original :",arr)
arr = np.sort(arr)[::-1]
print("Sorted in decsending order :",arr)

Original : [ 23   4  34  34   3 435   3  55   4]
Sorted in decsending order : [435  55  34  34  23   4   4   3   3]


In [8]:
arr = np.array([23,4,34,34,3,435,3,55,4]).reshape(3,3)
print("Original :",arr)
arr = np.sort(arr)
print("sorted :",arr) # by befault sort by row wise

Original : [[ 23   4  34]
 [ 34   3 435]
 [  3  55   4]]
sorted : [[  4  23  34]
 [  3  34 435]
 [  3   4  55]]


In [9]:
arr = np.array([23,4,34,34,3,435,3,55,4]).reshape(3,3)
print("Original :",arr)
arr = np.sort(arr,axis=1)
print("sorted :",arr) # sort by row wise

Original : [[ 23   4  34]
 [ 34   3 435]
 [  3  55   4]]
sorted : [[  4  23  34]
 [  3  34 435]
 [  3   4  55]]


In [10]:
arr = np.array([23,4,34,34,3,435,3,55,4]).reshape(3,3)
print("Original :",arr)
arr = np.sort(arr,axis=0)
print("sorted :",arr) #sort by col wise

Original : [[ 23   4  34]
 [ 34   3 435]
 [  3  55   4]]
sorted : [[  3   3   4]
 [ 23   4  34]
 [ 34  55 435]]


In [12]:
arr = np.array([23,4,34,34,3,435,3,55,4]).reshape(3,3)
print("Original :",arr)
arr = arr.flatten()
arr = np.sort(arr).reshape(3,3)
print("sorted :",arr) # by befault sort by row wise

Original : [[ 23   4  34]
 [ 34   3 435]
 [  3  55   4]]
sorted : [[  3   3   4]
 [  4  23  34]
 [ 34  55 435]]
